### ISSUE TITLE
Chest "Sort" occasionally deletes inventory

### ISSUE THREAD

**Issue by Epic428** [GregTechCE/GregTech#1017]
Seems the sort button for chests is occasionally deleting the inventory. I have info obtained from log file. This is latest version of GTCE but I have seen it happen on previous versions as well.

```
[21:33:22] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at gregtech.api.util.GTUtility.lambda$createItemStackComparator$4(GTUtility.java:722) ~[GTUtility.class:?]
	at gregtech.api.util.GTUtility$$Lambda$1204/1583962498.apply(Unknown Source) ~[?:?]
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469) ~[?:1.8.0_51]
	at java.util.Comparator$$Lambda$105/1183810313.compare(Unknown Source) ~[?:?]
	at java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:217) ~[?:1.8.0_51]
	at java.util.Comparator$$Lambda$106/103259134.compare(Unknown Source) ~[?:?]
	at java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:216) ~[?:1.8.0_51]
	at java.util.Comparator$$Lambda$106/103259134.compare(Unknown Source) ~[?:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351) ~[?:1.8.0_51]
	at java.util.TimSort.sort(TimSort.java:216) ~[?:1.8.0_51]
	at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_51]
	at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_51]
	at gregtech.common.metatileentities.storage.MetaTileEntityChest.sortInventorySlotContents(MetaTileEntityChest.java:282) ~[MetaTileEntityChest.class:?]
	at gregtech.common.metatileentities.storage.MetaTileEntityChest.lambda$createUI$1(MetaTileEntityChest.java:239) ~[MetaTileEntityChest.class:?]
	at gregtech.common.metatileentities.storage.MetaTileEntityChest$$Lambda$1176/1656641899.accept(Unknown Source) ~[?:?]
	at gregtech.api.gui.widgets.ClickButtonWidget.handleClientAction(ClickButtonWidget.java:85) ~[ClickButtonWidget.class:?]
	at gregtech.api.net.NetworkHandler.lambda$init$10(NetworkHandler.java:196) ~[NetworkHandler.class:?]
	at gregtech.api.net.NetworkHandler$$Lambda$219/1009889405.execute(Unknown Source) ~[?:?]
	at gregtech.api.net.NetworkHandler.lambda$onServerPacket$15(NetworkHandler.java:294) ~[NetworkHandler.class:?]
	at gregtech.api.net.NetworkHandler$$Lambda$1200/2093582260.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

```

**Comment by PowerForSeconds** [comment]
`Caused by: java.lang.NullPointerException`
Something's not sorting properly, and so it doesn't return ANYTHING for the result of the sorting, which leaves the chest empty. Is there anyway to do some sort of Try, Except like in python?

**Comment by Epic428** [comment]
https://clips.twitch.tv/RoundLazyTapirNononoCat

here's a clip of it happening. in my experience it seems to be more frequent when items aren't sequentially located in the slots.

**Comment by PowerForSeconds** [comment]
Huh.

**Comment by Epic428** [comment]
Lol I typed that and thought to myself that it might be confusing the way it was written.

In my testing it seems to happen more frequently if items aren’t placed in chest slots one after another and there’s open spaces between the items.

In addition, it doesn’t seem like it is a specific item or items that Cause it to happen. I could place the same items in a chest and consistently get different results and I could do this with any item I choose.

**Comment by PowerForSeconds** [comment]
Well, I don't know much about modding, so I can't really help you.
