### ISSUE TITLE
Error: failed to load data for block entity gregtech:surface_rock

### ISSUE THREAD

**Issue by DMTfarc** [GregTechCE/GregTech#1086]
This error constantly spamming in the console every minute.
Server: Spongeforge 7.2.1
Plugins: FastAsyncWorldEdit(19.11.13), LuckPerms(5.0.39)
Mods: Baubles(152), Botania(110-363), CodeChicken Lib(3.2.3.358), **GregTech Community Edition(1.9.1.505)**, MrCrayfish's Furniture Mod(631), Pam's HarvestCraft(1122zg), Thaumcraft(6.1b26), The Twilight Forest(3.10.1013)
`[12:38:18] [Server thread/ERROR] [FML]: A TileEntity gregtech:surface_rock(gregtech.common.blocks.surfacerock.TileEntitySurfaceRock) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
        at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[12:38:18] [Server thread/ERROR] [minecraft/TileEntity]: Failed to load data for block entity gregtech:surface_rock
java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
        at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[12:38:18] [Server thread/ERROR] [FML]: A TileEntity gregtech:surface_rock(gregtech.common.blocks.surfacerock.TileEntitySurfaceRock) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
        at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[12:38:18] [Server thread/ERROR] [minecraft/TileEntity]: Failed to load data for block entity gregtech:surface_rock
java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
        at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[12:38:18] [Server thread/ERROR] [FML]: A TileEntity gregtech:surface_rock(gregtech.common.blocks.surfacerock.TileEntitySurfaceRock) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
        at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
`

**Comment by LAGIdiot** [comment]
This looks similar to #1069. Please provide information regarding Forge version.

**Comment by Eatric** [comment]
The same error.
GregTechCE Version: 1.9.1.505
Forge Version: 14.23.5.2847

[crash-2020-05-25_20.44.07-client.txt](https://github.com/GregTechCE/GregTech/files/4678360/crash-2020-05-25_20.44.07-client.txt)

**Comment by LAGIdiot** [comment]
As stated in #1069 case. Problem is related to using **vanilafix** which is messing up with (or maybe fixing) NBT data in a way that GTCE is not anticipating.

**Comment by Eatric** [comment]
> 
> 
> As stated in #1069 case. Problem is related to using **vanilafix** which is messing up with (or maybe fixing) NBT data in a way that GTCE is not anticipating.

Thanks, I just delete **vanilafix**

**Comment by DMTfarc** [comment]
I'm using forge 14.23.5.2854. No fixing mods installed.

**Comment by LAGIdiot** [comment]
I am kind of lost at this one. I did not ever tested GTCE together with Spongeforge. And I am not even sure if GTCE supports running on Spongeforge officially. @pyure what is your take on it?

**Comment by pyure** [comment]
* Does issue always persist for the user, after reloading the world?
* Does issue persist after creating a new world?
* Does issue persist after removing other mods? (I noticed the modlist was tiny)

I did hit an NPE with surface rocks last week but I couldn't reproduce it.  I was flying around quickly in creative mode at the time.  No idea if its connected.

**Comment by DMTfarc** [comment]
- I just restarted the server, the error appears on preparing the spawn area.
`
[20:17:03] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing start region for world world (minecraft:overworld/0)
[20:17:04] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 8%
[20:17:05] [Server thread/ERROR] [net.minecraft.tileentity.TileEntity]: Failed to load data for block entity gregtech:surface_rock
java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
	at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.redirect$zmd000$impl$ProvideChunkForced(ChunkProviderServer.java:1642) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.server.MinecraftServer.bridge$prepareSpawnArea(MinecraftServer.java:4440) [MinecraftServer.class:?]
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:882) [WorldManager.class:1.12.2-2838-7.2.1]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:820) [WorldManager.class:1.12.2-2838-7.2.1]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4390) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
`
- I removed all the mods **except GTCE(1.9.1.505) and CodeChickenLib(3.2.3.358)** then I created a new world. I joined the server in creative mode(I'm the only player). When I got away from the spawn point, the issue appears. As the new chunks were generated, errors began spamming in the console.
`
[20:29:53] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Ryann_Z joined the game
[20:30:14] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Opped ryann_z
[20:30:21] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ryann_Z: Set own game mode to Creative Mode]
[20:30:46] [Server thread/ERROR] [net.minecraft.tileentity.TileEntity]: Failed to load data for block entity gregtech:surface_rock
java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
	at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) [amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:305) [amu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:911) [amu.class:?]
	at net.minecraft.world.WorldEntitySpawner.canCreatureTypeSpawnBody(WorldEntitySpawner.java:233) [anb.class:?]
	at net.minecraft.entity.EntityLiving$SpawnPlacementType.canSpawnAt(EntityLiving.java:1463) [vq$a.class:?]
	at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:226) [anb.class:?]
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:135) [anb.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[20:30:46] [Server thread/ERROR] [FML]: A TileEntity gregtech:surface_rock(gregtech.common.blocks.surfacerock.TileEntitySurfaceRock) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
	at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) [amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:305) [amu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:911) [amu.class:?]
	at net.minecraft.world.WorldEntitySpawner.canCreatureTypeSpawnBody(WorldEntitySpawner.java:233) [anb.class:?]
	at net.minecraft.entity.EntityLiving$SpawnPlacementType.canSpawnAt(EntityLiving.java:1463) [vq$a.class:?]
	at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:226) [anb.class:?]
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:135) [anb.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
`

**Comment by DMTfarc** [comment]
[latest(with all mods).log](https://github.com/GregTechCE/GregTech/files/4682236/latest.with.all.mods.log)
[latest(only GTCE).log](https://github.com/GregTechCE/GregTech/files/4682253/latest.only.GTCE.log)

**Comment by Freebi85** [comment]
[crash-2020-05-27_17.43.38-server.txt](https://github.com/GregTechCE/GregTech/files/4689932/crash-2020-05-27_17.43.38-server.txt)
Gonna add my crashreport on this as well. 
GregTechCE Version: 1.9.1.505
Forge Version: 14.23.5.2847

**Comment by LAGIdiot** [comment]
@Freebi85 I have created separated issue for your case as it is different from this one.
@DMTfarc as workaround use Forge version: 14.23.5.2847.

**Comment by DMTfarc** [comment]
Issue solved by using forge 14.23.5.2847.
