### ISSUE TITLE
[Bug] Steel Chest Sorting Error

### ISSUE THREAD

**Issue by DeckerCHAN** [GregTechCE/GregTech#1095]
All items are gone from Steel Chest

```
[07:39:42] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task                                                                                                  [11/1983]
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_252]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
        at gregtech.api.util.GTUtility.lambda$createItemStackComparator$4(GTUtility.java:722) ~[GTUtility.class:?]
        at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469) ~[?:1.8.0_252]
        at java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:217) ~[?:1.8.0_252]
        at java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:216) ~[?:1.8.0_252]
        at java.util.TimSort.binarySort(TimSort.java:296) ~[?:1.8.0_252]
        at java.util.TimSort.sort(TimSort.java:221) ~[?:1.8.0_252]
        at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_252]
        at java.util.ArrayList.sort(ArrayList.java:1462) ~[?:1.8.0_252]
        at gregtech.common.metatileentities.storage.MetaTileEntityChest.sortInventorySlotContents(MetaTileEntityChest.java:282) ~[MetaTileEntityChest.class:?]

```

**Comment by pyure** [comment]
Should be fixed via #1017.  Can you please confirm which version of GT you're using, which forge version you're using and whether you're playing on a server?

**Comment by DeckerCHAN** [comment]
Latest Infitech 3 therefore gregtech-1.12.2-1.9.0.481.jar

**Comment by pyure** [comment]
Latest Infitech3 hasn't updated GT in a while; if you're feeling ambitious, can you try updating GT locally and seeing if its still a problem?

**Comment by LAGIdiot** [comment]
This one is exactly same as #1043. On which I did some intensive testing to find if it was fixed and I came to conclusion that it was. This is just matter of upgrading GTCE to version 1.9.1.505 or newer.

Feel free to reopen if problem is still present after upgrade.
