### ISSUE TITLE
Crash server when player takes damage from lava.

### ISSUE THREAD

**Issue by IvanTabakerka** [GregTechCE/GregTech#1101]
The server restarts after an error.
When the player takes damage from lava.

**Console log**
```
> (16:26:43|INFO): MoZerator lost connection: Internal server error
> (16:26:43|ERROR): Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:476) ~[oq.class:?]
at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:519) ~[pl.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:1216) ~[pa.class:?]
at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:364) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:223) ~[oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:884) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:478) ~[nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:739) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/common/ISpecialArmor$ArmorProperties
at net.minecraft.entity.EntityLivingBase$3.apply(EntityLivingBase.java:1428) ~[vp$3.class:?]
at net.minecraft.entity.EntityLivingBase$3.apply(EntityLivingBase.java:1424) ~[vp$3.class:?]
at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1435) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(EntityPlayer.java:1170) ~[aed.class:?]
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:922) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1066) ~[aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:715) ~[oq.class:?]
at net.minecraft.entity.Entity.func_70081_e(Entity.java:1361) ~[vg.class:?]
at net.minecraft.entity.Entity.func_70091_d(Entity.java:1179) ~[vg.class:?]
at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1998) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1959) ~[aed.class:?]
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2372) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:500) ~[aed.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2194) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) ~[aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:392) ~[oq.class:?]
... 9 more
> (16:26:43|ERROR): This crash report has been saved to: /home/container/./crash-reports/crash-2020-06-08_16.26.43-server.txt
```
[crash-2020-06-08_16.26.43-server.txt](https://github.com/GregTechCE/GregTech/files/4746225/crash-2020-06-08_16.26.43-server.txt)

**Comment by LAGIdiot** [comment]
I don't see anything GTCE related on first look. Can you please be more descriptive about what happened? I am interested mostly in information regarding what armor crashing player had equipped but I will take anything that can help me find out what caused the crash. Also is this one time thing or is it something that happens every time?

**Comment by IvanTabakerka** [comment]
https://yadi.sk/i/CigdrtrVv2tO8Q
Only GTCE is installed on the server.

**Comment by IvanTabakerka** [comment]
Thanks for the answer
