### ISSUE TITLE
在catserver服务端上刷报错 无法加载表层岩石

### ISSUE THREAD

**Issue by zhangziming666** [GregTechCE/GregTech#1122]
[07:44:07] [Server thread/ERROR]: A TileEntity gregtech:surface_rock(gregtech.common.blocks.surfacerock.TileEntitySurfaceRock) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
        at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:128) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:498) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:git-CatServer-1.12.2-de0a1c1]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:151) [ChunkIOExecutor.class:git-CatServer-1.12.2-de0a1c1]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
希望可以修复

**Comment by DeckerCHAN** [comment]
1. Is this happens constantly or occasionally? What has to be done to reproduce the issue?
2. What version of GTCE you are using？ What version of forge you are using?
3. If you can't reproduce the issue on pure forge server, try contact CatServer's dev.
4. 尽量别用中文，没人能看懂

**Comment by zhangziming666** [comment]
> 1. 这是持续发生还是偶尔发生？重现该问题该怎么做？
> 2. 您正在使用哪个版本的GTCE？您正在使用哪个版本的伪造？
> 3. 如果无法在纯Forge服务器上重现该问题，请尝试与CatServer的开发人员联系。
> 4. 尽量别用中文，没人能看懂

This has always been the case, and the server has been brushing the background all the time

Then the minerals do not form

I used gtce of 1.9.1.505

**Comment by LAGIdiot** [comment]
Hi, this is **know bug** which has already been **fixed**. Please upgrade **GTCE** to newest version (**1.9.2.515**).

Also this does not look like pure Forge server so there may be needed additional steps to make it work correctly. I can suggest removal of all Surface Rocks via some world editing tool if your server does not start correctly.

Please let us know if you were able to fix this problem or additional help is needed.

**Comment by LAGIdiot** [comment]
Is this still relevant? Does this problem still occurs after suggested upgrade?

**Comment by LAGIdiot** [comment]
I am closing this issue as stale. If there is still required any action from GTCE side then feel free to re-open this issue.
