### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by railken** [GregTechCE/GregTech#145]
Server crashed while fighting a mob with a cobalt pickaxe

```
[net.minecraft.server.MinecraftServer]: Caused by: java.lang.NoSuchMethodError: gregtech.api.items.toolitem.IToolStats.getMiningSound(Lnet/minecraft/item/ItemStack;)Lnet/minecraft/util/ResourceLocation;
        at gregtech.api.items.toolitem.ToolMetaItem.func_179218_a(ToolMetaItem.java:224) ~[ToolMetaItem.class:?]
        at net.minecraft.item.ItemStack.func_179548_a(ItemStack.java:376) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:320) ~[or.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:109) ~[or.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:316) ~[oq.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:172) ~[TrackingUtil.class:1.12.2-2705-7.1.0-BETA-3171]
        at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zlk000(WorldServer.java:2881) ~[oo.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:4154) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642) ~[oo.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:6558) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2222) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
```

**Comment by Archengius** [comment]
fixed in dev
