### ISSUE TITLE
gtce corrupts preexisting worlds when it is added

### ISSUE THREAD

**Issue by pulluro** [GregTechCE/GregTech#1490]
When i add gtce to my modpack and load up an preexisting world it will corrupt everything. If i generate a new world it won't cause an issue. I also setup an test environment where the configs were unmodified and the issue still persists. I am playing singleplayer. Now i also tried loading the world with just gregtech and core libraries, it still caused corruption. No idea what causes this. I would still really like to use gtce in my pack. Thanks!
Modlist: https://pastebin.com/MATeByjT

Forge: 14.23.5.2854
GTCE: 1.10.9.612

It first says this when i try to load up an world
![kuva](https://user-images.githubusercontent.com/79382866/108611872-98067180-73eb-11eb-87c4-ac4413bcfad5.png)
Then this
![kuva](https://user-images.githubusercontent.com/79382866/108611883-b2d8e600-73eb-11eb-8a83-b52892f4f24f.png)

**Comment by warjort** [comment]
Can  you provide the logs/latest.log when this happens.
The most likely cause is another mod having an error due to the presence of GTCE and not creating its blocks/items.

If there is no obvious error in the log, it would be helpful if you can determine the minimum set of mods to reproduce the problem. Preferably with no crafttweaker scripts or config changes.
I would start with the mentioned techguns mod and its dependencies.

Removing mods from an existing world will usually show that first message. Its blocks and items will likely be mentioned somewhere in the save file, even if you haven't physically used them.
So your second test of trying to load the world with just GTCE would be expected to fail.

**Comment by pulluro** [comment]
The resulting log file is about 140mb in size so i uploaded it to the cloud. It seems to be repeating an error and that's why it got so big.
Heres the log file: http://www.mediafire.com/file/bj9zgdmxegge5vx/latest.log/file
Now it happened to also crash when loading the world, it happens sometimes. Heres the server crash log https://pastebin.com/miYm3Epg, and heres the client crash log https://pastebin.com/xEuQSmRG
When it crashes it says, potential causes for crash are immersive engineering, mekanism. The corrupted items were ie textures so that might be the cause.

Now it's quite hard to find the minimum number of mods required to reproduce the problem because i only have an preexisting world with all these mods loaded. 
What i tried is: 1. Cut the amount of mods 2. Load the world so it removes the items from those mods 3. Add gtce and see for corruption. I got corruption until the very last mod with gtce. I don't know if this is a good method or not.
I used a clean instance with no config changes for testing.

I tried making a new world with my modpack (without gtce) then loading it with gtce and got no apparent corruption.
Regarding the message in the first screenshot, i got that after adding just gtce. Techguns and gtce seems to do something. I tried running it without techguns (and its dependencies) and there is still corruption being caused.

**Comment by warjort** [comment]
It is hard to see the wood for the trees there are so many errors.
I don't see anything that is related to GTCE, but you say you see it is causing this?

The first indication of an error is with some mixins (this might be normal? you would need to check if the original modpack has these errors)

````
[15:30:49] [Client thread/WARN] [mixin]: Error loading class: team/chisel/client/TextureStitcher$MagicStitchingSprite (java.lang.ClassNotFoundException: The specified class 'team.chisel.client.TextureStitcher$M
agicStitchingSprite' was not found)
[15:30:49] [Client thread/WARN] [mixin]: Error loading class: openblocks/client/renderer/tileentity/TileEntityTankRenderer (java.lang.ClassNotFoundException: The specified class 'openblocks.client.renderer.tile
entity.TileEntityTankRenderer' was not found)
[15:30:49] [Client thread/WARN] [mixin]: Error loading class: slimeknights/tconstruct/library/client/GuiUtil (java.lang.ClassNotFoundException: The specified class 'slimeknights.tconstruct.library.client.GuiUti
l' was not found)
[15:30:49] [Client thread/WARN] [mixin]: Error loading class: slimeknights/tconstruct/library/client/RenderUtil (java.lang.ClassNotFoundException: The specified class 'slimeknights.tconstruct.library.client.Ren
derUtil' was not found)
[15:30:49] [Client thread/WARN] [mixin]: Error loading class: morph/avaritia/client/render/item/HaloRenderItem (java.lang.ClassNotFoundException: The specified class 'morph.avaritia.client.render.item.HaloRende
rItem' was not found)
[15:30:49] [Client thread/WARN] [mixin]: Error loading class: morph/avaritia/client/render/item/WrappedItemRenderer (java.lang.ClassNotFoundException: The specified class 'morph.avaritia.client.render.item.Wrap
pedItemRenderer' was not found)
````

Then it starts to show lots of parsing errors in different ways.
The first is
````
[15:31:05] [Client thread/ERROR] [mts]: MTSERROR: MTSERROR: An error was encountered when trying to parse: mtsaircooled:mtsaircooled_emergencyvehicle_chevy_corvair95_1963
````
but there are many in the block models which looks like it is not finding things, including textures.

There are also some NullPointerExceptions from immersive petroleum and thermal.

Then it seems like all JEI is failing, which is probably not suprising if the mods can't parse their recipes as well.

Then we get to the error you reported which is not just techguns

````
[15:34:17] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world randomthings:plate_corrector
[15:34:17] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world randomthings:lapisglass
[15:34:17] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world draconicevolution:chaos_shard_atmos
[15:34:17] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world draconicevolution:creative_rf_source
[15:34:17] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world randomthings:advancedredstoneinterface
[15:34:17] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world littletiles:blocklittletiles
[15:34:17] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world draconicevolution:portal
[15:34:17] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world dungeontactics:lantern_iron
[15:34:17] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world techguns:block_milk
[15:34:17] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world dungeontactics:caltrops

it keep going....
````

**Comment by warjort** [comment]
On top of these there are warnings about signatures not matching and some mods not being proper mods.
Which also might be normal?

Are you sure you copied your original world properly?
All these parsing errors point towards missing or corrupted files 
but there might be some other reason why it cannot parse these files inside the mod jars.

**Comment by warjort** [comment]
On the crash
````
java.lang.IllegalStateException: Unable to get Y-rotated facing of down
    at net.minecraft.util.EnumFacing.rotateY(EnumFacing.java:113)
    at mctmods.immersivetechnology.common.blocks.metal.tileentities.TileEntityDistillerSlave.getAdvancedSelectionBounds(TileEntityDistillerSlave.java:227
````

This is probably related to the parsing issue with it not being able to load the block states?

**Comment by warjort** [comment]
There is this error as well
````
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
        at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
````
But it is later on.

It looks like you have too many blocks unless you use a mod like "Just enough ids"

**Comment by pulluro** [comment]
Yup, that was it. I didn't have that mod installed. Seems to work like a charm. Thank you for your help and sorry for wasting your time.

**Comment by LAGIdiot** [comment]
I am glad that cause of this problem was found and fixed.
Thanks @warjort for handling this case in my absence.
