### ISSUE TITLE
Games crashes when placing bronze tube inside compact machine

### ISSUE THREAD

**Issue by antofik** [GregTechCE/GregTech#1551]
https://github.com/GregTechCE/GregTech/blob/v1.10.0/src/main/java/gregtech/common/pipelike/fluidpipe/BlockFluidPipe.java#L134

Time: 2021-03-26 00:56:40 GMT
Description: Exception while ticking a block

```
java.lang.NullPointerException
    at gregtech.common.pipelike.fluidpipe.BlockFluidPipe.canPushIntoFluidHandler(BlockFluidPipe.java:134)
    at gregtech.common.pipelike.fluidpipe.BlockFluidPipe.getActiveNodeConnections(BlockFluidPipe.java:121)
    at gregtech.api.pipenet.block.BlockPipe.updateTick(BlockPipe.java:110)
    at net.minecraft.world.WorldServer.tickUpdates(WorldServer.java:737)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:223)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
```

Mod pack: FTB Interactions 2.0.9

The crash occured after I put the medium bronze tube on the wall of compact machine (inside), which was connected to another bronze tube with steam on outside (see https://www.curseforge.com/minecraft/mc-mods/compact-machines,  installed version compactmachines3-1.12.2-3.0.18-b278.jar)

Looks like Compact Machine mode creates virtual connections between pipes, but BlockFluidPipe tries to find TileEntity from inside of compact machine and fails to do so.

**Comment by warjort** [comment]
This issue here is the compact machine is pretending to be a fluid pipe by proxying its capability.
But when we ask it how big a pipe it is, it says "I don't know, I am not really a pipe".

It shouldn't crash in this circumstance, it should just refuse to work.

Otherwise you are going to get something similar to the infinite recursion of #1374 with the fluid sloshing backwards and forwards across the compact machine's tunnel. 
Normally this back and forth would be stopped by the size check that the compact machine is not allowing.

The correct way to make this work would be to put a tank on the destination side of the compact machine's tunnel and then pump from the tank into the destination pipes.
Or you could put a tank on the origin side and pump from it into the compact machine's tunnel.
Or any other solution that doesn't potentially have the fluid going both ways.

**Comment by antofik** [comment]
Yes, I think you are correct. I've tried to make a custom build where code returns 'false' if TileEntity is null - at least game loads good now. I'd say, from code perspective it would be good to make a null check there, since `getPipeTileEntity` could legitimately return null.

And thanks for suggestions of walk-around, that is most helpful!
