### ISSUE TITLE
duplicate ID[BUG] 

### ISSUE THREAD

**Issue by blakpsykozz27** [GregTechCE/GregTech#1688]
**Describe the bug**
there is an ID duplication with the GregtechEnergestic mod
which causes a crash at launch
I also report it to the author of the mod

**Versions** 1.12.2
Forge: 14.23.5.2847
GTCE: 1.16.1.753
_Modpack:_
_Addons:_ GregtechEnergestic 1.0.0.3

**Setup**
Playing Solo

**Steps To Reproduce**
put gregtech and gregtechenergistics together the crash game and said that there is an element that has the same id

**Expected behavior**

**Screenshots**
Time: 7/1/21 4:21 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GregTech Energistics (gregtechenergistics)
Caused by: java.lang.IllegalArgumentException: Tried to reassign id 40 to gregtech.api.cover.CoverDefinition@45d1d5c3 (gregtechenergistics:ae2.interface.lv), but it is already assigned to gregtech.api.cover.CoverDefinition@68046b55 (gregtech:fluid.regulator.lv)!
	at gregtech.api.util.GTControlledRegistry.register(GTControlledRegistry.java:50)
	at gregtech.api.cover.CoverDefinition.registerCover(CoverDefinition.java:28)
	at com.soliddowant.gregtechenergistics.covers.CoverBehaviors.registerBehavior(CoverBehaviors.java:41)
	at com.soliddowant.gregtechenergistics.covers.CoverBehaviors.registerStockerCover(CoverBehaviors.java:34)
	at com.soliddowant.gregtechenergistics.covers.CoverBehaviors.init(CoverBehaviors.java:19)
	at com.soliddowant.gregtechenergistics.CommonProxy.init(CommonProxy.java:24)
	at com.soliddowant.gregtechenergistics.ClientProxy.init(ClientProxy.java:19)
	at com.soliddowant.gregtechenergistics.GregTechEnergisticsMod.init(GregTechEnergisticsMod.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Additional context**

**Comment by SpeeeDCraft** [comment]
same problem

**Comment by DStrand1** [comment]
See: https://github.com/solidDoWant/GregTech-Energistics/issues/2
