### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yuhaome** [GregTechCE/GregTech#1737]
Game Mode: Single player
Forge:14.23.5.2860
Optifine:HD_U_G5
Game version:1.12.2

Question:Whenever I enter the nether,The game crashes.
Error reports are: [Client thread/FATAL] [FML]: Suppressed additional 411 model loading errors for domain gregtech;[Client thread/FATAL] [FML]: Suppressed additional 3 model loading errors for domain twilightforest;

Here's the log:[logs.log](https://github.com/GregTechCE/GregTech/files/7836224/logs.log)

I hope someone sees it,thanks.

**Comment by Exaxxion** [comment]
Are you able to reproduce this issue without Optifine?

**Comment by yuhaome** [comment]
>I just tested deleting optifine and it still crashed,I am now in the Nether dimension.So when entering the archive, it will crash directly.

**Comment by warjort** [comment]
The actual error is this:

````
java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:542)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at gregtech.api.worldgen.generator.CachedGridEntry$ChunkDataEntry.populateChunk(CachedGridEntry.java:359)
	at gregtech.api.worldgen.generator.CachedGridEntry.populateChunk(CachedGridEntry.java:174)
	at gregtech.api.worldgen.generator.WorldGeneratorImpl.generateInternal(WorldGeneratorImpl.java:49)
	at gregtech.api.worldgen.generator.WorldGeneratorImpl.generate(WorldGeneratorImpl.java:40)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
````

This appears to be some problem with GTCE trying to set a block in a chunk.
````World.func_180501_a````
is World.setBlockState()

This is the ore generation, so it might be a problem with any custom (ore) configuration you have for the nether.
NOTE: Gregicality modifies the ore generation.

Otherwise:

Just before this error there are these messages:

````
07:37:24] [Server thread/WARN] [FML]: LightArea loaded a new chunk [11, -10] in dimension -1 (the_nether) while populating chunk [11, -9], causing cascading worldgen lag.
[07:37:24] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[07:37:24] [Server thread/WARN] [FML]: LightArea loaded a new chunk [8, -13] in dimension -1 (the_nether) while populating chunk [11, -10], causing cascading worldgen lag.
[07:37:24] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
````

and just before that

````
[07:37:22] [Client thread/WARN] [Config]: [OptiFine] java.lang.NullPointerException null
[07:37:22] [Client thread/WARN] [Config]: [OptiFine] Error finding Chunk.hasEntities
[07:37:22] [Client thread/INFO] [net.optifine.Log]: [OptiFine] (Reflector) Field not present: net.minecraft.world.chunk.Chunk.hasEntities
````

I would guess there is some kind of mod incompability between GTCE, LightArea or OptiFine
But it might be a different mod (not mentioned in the log) triggering a problem in these mods.

The only thing I can suggest is making a copy of your world and then try removing mod(s) until you find the problem mod(s).

The likely candidates are these core mods since these can change the core minecraft code:
````
WARNING: coremods are present:
  CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  GTCELoadingPlugin (gregtech-1.12.2-1.17.1.770.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  MekanismCoremod (Mekanismé€šç”¨æœºæ¢°.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-33.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  GACoreMod (Gregicality-1.12.2-0.23.3.jar)
  JechCore (JustEnoughCharacters-1.12.0-3.5.1.jar)
  HCASM (HammerLib-1.12.2-2.0.6.31.jar)
Contact their authors BEFORE contacting forge
````

**Comment by yuhaome** [comment]
Thank you. I finally know what the problem is,The reason is that I changed the mineral generation Settings for GTCE，Now I've created an archive copy，And delete the previous configuration file，Sorry for the inconvenience。
