### ISSUE TITLE
[BUG]: Network crash due to enchanted tools available in inventory

### ISSUE THREAD

**Issue by Lolothepro** [GregTechCE/GregTech#1766]
```
io.netty.handler.codec.EncoderException: Failed to encode packet 'serverbound/minecraft:set_creative_mode_slot'
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:55) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:14) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.0.20-beta/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:104) ~[neoforge-21.0.20-beta-universal.jar%23186!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.0.20-beta/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:39) ~[neoforge-21.0.20-beta-universal.jar%23186!/:?] {re:classloading}
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar%23116!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.Connection$2.write(Connection.java:528) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.Connection.doSendPacket(Connection.java:364) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.Connection.lambda$sendPacket$12(Connection.java:359) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading,re:mixin}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23117!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar%23124!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23117!/:4.1.97.Final] {}
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23117!/:4.1.97.Final] {}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
Caused by: java.lang.IllegalArgumentException: Can't find id for 'Reference{ResourceKey[minecraft:enchantment / minecraft:fortune]=Enchantment Fortune}' in map net.minecraft.core.Registry$1@1079b87b
	at TRANSFORMER/minecraft@1.21/net.minecraft.core.IdMap.getIdOrThrow(IdMap.java:27) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.ByteBufCodecs$25.encode(ByteBufCodecs.java:479) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.ByteBufCodecs$25.encode(ByteBufCodecs.java:464) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.ByteBufCodecs$22.lambda$encode$0(ByteBufCodecs.java:405) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2IntMap.lambda$forEach$0(Object2IntMap.java:245) ~[fastutil-8.5.12.jar%23125!/:?] {re:mixin}
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapEntrySet.fastForEach(Object2IntOpenHashMap.java:1078) ~[fastutil-8.5.12.jar%23125!/:?] {}
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.objects.Object2IntMap.forEach(Object2IntMap.java:247) ~[fastutil-8.5.12.jar%23125!/:?] {re:mixin}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.ByteBufCodecs$22.encode(ByteBufCodecs.java:404) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.ByteBufCodecs$22.encode(ByteBufCodecs.java:401) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$8.encode(StreamCodec.java:156) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.core.component.DataComponentPatch$1.encodeComponent(DataComponentPatch.java:127) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.core.component.DataComponentPatch$1.encode(DataComponentPatch.java:111) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.core.component.DataComponentPatch$1.encode(DataComponentPatch.java:58) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.ItemStack$1.encode(ItemStack.java:151) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.ItemStack$1.encode(ItemStack.java:131) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.ItemStack$3.encode(ItemStack.java:215) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.ItemStack$3.encode(ItemStack.java:203) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$8.encode(StreamCodec.java:157) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:97) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:87) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[client-1.21-20240613.152323-srg.jar%23185!/:?] {re:classloading}
```

**Comment by Exaxxion** [comment]
You appear to be playing GTCEu Modern. Please report issues for that mod to its repository: https://github.com/GregTechCEu/GregTech-Modern/issues
