### ISSUE TITLE
PrimitiveBlastFurnaceRecipe lacks remove() method

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#242]
**GT**: gregtech-1.12.2-0.4.7.39.jar

```
// Remove recipes from PBF
val pbf_recipes = mods.gregtech.recipe.RecipeMaps.getPrimitiveBlastFurnaceRecipes();
for pbf_recipe in pbf_recipes {  
  pbf_recipe.remove();
}
```

```
[INITIALIZATION][CLIENT][ERROR] gregtech.zs:13 > No such member in gregtech.api.recipes.recipes.PrimitiveBlastFurnaceRecipe: remove
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: gregtech.zs}: null
java.lang.NullPointerException
	at Gregtech.__script__(gregtech.zs:13)
	at __ZenMain__.run(Gregtech)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:174)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:68)
	at crafttweaker.runtime.CrTTweaker.load(CrTTweaker.java:62)
	at crafttweaker.CrafttweakerImplementationAPI.load(CrafttweakerImplementationAPI.java:115)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_311_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Exidex** [comment]
Example:
```
import mods.gregtech.recipe.RecipeMaps;

for recipe in RecipeMaps.getPrimitiveBlastFurnaceRecipes() {
    recipe.remove();
}
```
