### ISSUE TITLE
Running on server problems

### ISSUE THREAD

**Issue by Timozer** [GregTechCE/GregTech#292]
Hi,

I install this mod on the server, but it seems that there is something wrong. I don't know how to do.
Can you help me?

```sh
---- Minecraft Crash Report ----

WARNING: coremods are present:
  JechCore (JustEnoughCharacters-1.12.0-2.3.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 8/31/18 6:20 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: gregtech/api/render/MetaTileEntityRenderer
	at gregtech.api.block.machines.BlockMachine.func_149645_b(BlockMachine.java:301)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185901_i(BlockStateContainer.java:356)
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.cover.CoverManager.isModelSupported(CoverManager.java:160)
	at com.raoulvdberge.refinedstorage.apiimpl.network.node.cover.CoverManager.isValidCover(CoverManager.java:156)
	at com.raoulvdberge.refinedstorage.item.ItemCover.func_150895_a(ItemCover.java:119)
	at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:38)
	at crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:64)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_66_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:762)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: gregtech.api.render.MetaTileEntityRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: codechicken/lib/render/item/IItemRenderer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 22 more
Caused by: java.lang.ClassNotFoundException: codechicken.lib.render.item.IItemRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 28 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.model.IBakedModel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@65f00478 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 34 more
Caused by: java.lang.RuntimeException: Attempted to load class cfy for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 36 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-33-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4253146576 bytes (4056 MB) / 4881121280 bytes (4655 MB) up to 4881121280 bytes (4655 MB)
	JVM Flags: 2 total; -Xmx5120M -Xms4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2758 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                  | Source                                              | Signature                                |
	|:----- |:--------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.2                   | minecraft.jar                                       | None                                     |
	| UCH   | mcp                   | 9.42                     | minecraft.jar                                       | None                                     |
	| UCH   | FML                   | 8.0.99.99                | forge-1.12.2-14.23.4.2758-universal.jar             | None                                     |
	| UCH   | forge                 | 14.23.4.2758             | forge-1.12.2-14.23.4.2758-universal.jar             | None                                     |
	| UCH   | jecharacters          | 1.12.0-2.3.2             | JustEnoughCharacters-1.12.0-2.3.2.jar               | None                                     |
	| UCH   | opencomputers|core    | 1.7.2.67                 | minecraft.jar                                       | None                                     |
	| UCH   | appliedenergistics2   | rv5-stable-11            | [AE2存储]appliedenergistics2-rv5-stable-11.jar        | None                                     |
	| UCH   | buildcraftlib         | 7.99.17                  | [BC建筑]buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftcore        | 7.99.17                  | [BC建筑]buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftbuilders    | 7.99.17                  | [BC建筑]buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftenergy      | 7.99.17                  | [BC建筑]buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftfactory     | 7.99.17                  | [BC建筑]buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftrobotics    | 7.99.17                  | [BC建筑]buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcrafttransport   | 7.99.17                  | [BC建筑]buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | buildcraftsilicon     | 7.99.17                  | [BC建筑]buildcraft-7.99.17.jar                        | None                                     |
	| UCH   | codechickenlib        | 3.2.1.351                | [GTCE]CodeChickenLib-1.12.2-3.2.1.351-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | crafttweaker          | 4.1.9                    | [GTCE]CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
	| UCH   | jei                   | 4.11.0.212               | [JEI]jei_1.12.2-4.11.0.212.jar                      | None                                     |
	| UCH   | crafttweakerjei       | 2.0.2                    | [GTCE]CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
	| UCH   | forgemultipartcbe     | 2.5.0.71                 | [GTCE]ForgeMultipart-1.12.2-2.5.0.71-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | microblockcbe         | 2.5.0.71                 | [GTCE]ForgeMultipart-1.12.2-2.5.0.71-universal.jar  | None                                     |
	| UCH   | minecraftmultipartcbe | 2.5.0.71                 | [GTCE]ForgeMultipart-1.12.2-2.5.0.71-universal.jar  | None                                     |
	| UCH   | gregtech              | 0.5.7.54                 | [GT格雷科技]gregtech-1.12.2-0.5.7.54.jar                | None                                     |
	| UCH   | trackapi              | 1.1                      | TrackAPI-1.1_1.12.jar                               | None                                     |
	| UCH   | theoneprobe           | 1.4.23                   | theoneprobe-1.12-1.4.23.jar                         | None                                     |
	| UCH   | immersiveengineering  | 0.12-84                  | [IE科技]ImmersiveEngineering-0.12-84.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | immersiverailroading  | 1.3.2                    | [IR铁路]ImmersiveRailroading-1.3.2_1.12.jar           | None                                     |
	| UCH   | nei                   | 2.4.1                    | [NEI]NotEnoughItems-1.12.2-2.4.1.238-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | refinedstorage        | 1.6.3                    | [存储]refinedstorage-1.6.3.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCH   | gokistats             | @version@                | gokiStats-1.2.3.1.jar                               | None                                     |
	| UCH   | igwmod                | 1.4.4-15                 | IGW-Mod-1.12.2-1.4.4-15-universal.jar               | None                                     |
	| UCH   | infinitylib           | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                              | None                                     |
	| UCH   | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | opencomputers         | 1.7.2.67                 | OpenComputers-MC1.12.2-1.7.2.67.jar                 | None                                     |
	| UCH   | wanionlib             | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                            | None                                     |

	Loaded coremods (and transformers): 
JechCore (JustEnoughCharacters-1.12.0-2.3.2.jar)
  me.towdium.jecharacters.core.JechClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Archengius** [comment]
are you sure you are running on latest build?

**Comment by Timozer** [comment]
There is no problem when i play it on windows and mac pc with same version of forge(2758) and same version of GregTech CE. Actually, except some client mods such as BetterFPS, IGW(in game wiki), Inventory Tweaks, all mods i used have the same version. I tested it with generating world on the server or generating a world on the local pc and then uploading it to the server, both didn't work. >_<

**Comment by Archengius** [comment]
because it is Refined Storage thinking that client-side-only things work properly on server side.
I already fixed that, consider using latest build
