### ISSUE TITLE
Invalid WorldSceneRenderer properties and unnecessary block updates

### ISSUE THREAD

**Issue by LemADEC** [GregTechCE/GregTech#469]
When starting the game with
 gregtech-1.12.2-1.0.124
 jei_1.12.2-4.12.1.217
 CodeChickenLib-1.12.2-3.2.2.353,
an invalid call to setBlockState() is done during client boot:
- the fake world used is declared as server side (isRemote is false).
- the fake world is reporting as the overworld (dimension id is 0).
- no flag is set, defaulting to 3 which will notify neighboring blocks, causing forge to trigger unneeded events.
- a blockstate is set before properly loading the world and chunks (i.e. triggering the related events).
This impacts loading time and may corrupt other mods world data.

Consider at least fixing the first 3 points so other mods can easily filter out this world.

**Comment by LemADEC** [comment]
Here's the related callstack in my dev space:
```
at cr0s.warpdrive.event.ChunkHandler.getChunkData(ChunkHandler.java:261)
at cr0s.warpdrive.event.ChunkHandler.onBlockUpdated(ChunkHandler.java:236)
at cr0s.warpdrive.event.WorldHandler.onBlockUpdated(WorldHandler.java:134)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_78_WorldHandler_onBlockUpdated_BlockEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.event.ForgeEventFactory.onNeighborNotify(ForgeEventFactory.java:162)
at net.minecraft.world.World.notifyNeighborsOfStateChange(World.java:576)
at net.minecraft.world.World.notifyNeighborsRespectDebug(World.java:519)
at net.minecraft.world.World.markAndNotifyBlock(World.java:451)
at net.minecraft.world.World.setBlockState(World.java:431)
at gregtech.api.render.scene.WorldSceneRenderer$TrackedDummyWorld.setBlockState(WorldSceneRenderer.java:292)
at net.minecraft.world.World.setBlockState(World.java:501)
at gregtech.api.util.BlockInfo.apply(BlockInfo.java:47)
at gregtech.api.render.scene.WorldSceneRenderer.<init>(WorldSceneRenderer.java:61)
at gregtech.integration.jei.multiblock.MultiblockInfoRecipeWrapper.initializeSceneRenderer(MultiblockInfoRecipeWrapper.java:218)
at gregtech.integration.jei.multiblock.MultiblockInfoRecipeWrapper$$Lambda$554/523201512.apply(Unknown Source)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
at gregtech.integration.jei.multiblock.MultiblockInfoRecipeWrapper.<init>(MultiblockInfoRecipeWrapper.java:53)
at gregtech.integration.jei.multiblock.MultiblockInfoCategory.registerRecipes(MultiblockInfoCategory.java:25)
at gregtech.integration.jei.GTJeiPlugin.register(GTJeiPlugin.java:56)
at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:181)
at mezz.jei.startup.JeiStarter.start(JeiStarter.java:64)
at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:120)
at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:626)
at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
at net.minecraft.client.Minecraft.init(Minecraft.java:582)
at net.minecraft.client.Minecraft.run(Minecraft.java:422)
at net.minecraft.client.main.Main.main(Main.java:118)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
at GradleStart.main(GradleStart.java:25)
```

**Comment by Archengius** [comment]
Just removed event triggering and changed world ID to be sure. Should be enough for most actions.
