### ISSUE TITLE
Exception in modifyFuelBurnTime trying to access missing block field

### ISSUE THREAD

**Issue by LemADEC** [GregTechCE/GregTech#482]
As of 1.12.2-1.0.124, the mod is trying to access a missing block field while modifying fuel burn time.
I can only reproduce in dev space, not sure why, maybe some obfuscation issue or different mappings than stable_39.

```
[04:35:18] [Client thread/ERROR] [jei]: Failed to get tooltip: 1xtile.compressed@5 gregtech:compressed_2
java.lang.NoSuchFieldError: block
	at gregtech.common.CommonProxy.modifyFuelBurnTime(CommonProxy.java:185) ~[CommonProxy.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_17_CommonProxy_modifyFuelBurnTime_FurnaceFuelBurnTimeEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.getItemBurnTime(ForgeEventFactory.java:270) ~[ForgeEventFactory.class:?]
	at cr0s.warpdrive.event.TooltipHandler.onTooltipEvent_last(TooltipHandler.java:88) ~[TooltipHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_112_TooltipHandler_onTooltipEvent_last_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:335) ~[ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:993) ~[ItemStack.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:40) [ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:21) [ItemStackRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.getIngredientTooltipSafe(IngredientRenderer.java:140) [IngredientRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.getTooltip(IngredientRenderer.java:111) [IngredientRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.drawTooltip(IngredientRenderer.java:89) [IngredientRenderer.class:?]
	at mezz.jei.gui.overlay.IngredientGrid.drawTooltips(IngredientGrid.java:114) [IngredientGrid.class:?]
	at mezz.jei.gui.overlay.IngredientGridAll.drawTooltips(IngredientGridAll.java:94) [IngredientGridAll.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.drawTooltips(IngredientListOverlay.java:188) [IngredientListOverlay.class:?]
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:82) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_221_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:397) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1177) [EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1209) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:442) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
```

**Comment by Archengius** [comment]
this is my field in my class, and it exists
only reason i can think of is somebody's fucked up coremod transformer.

**Comment by LemADEC** [comment]
The block property already exists in the parent class and it's protected, while yours is public.
Since they're both overlapping, I guess it's a bit unpredictable.
I had same issue in my mod and preferred to use the ItemBlock.getBlock() method for external usage.

**Comment by Archengius** [comment]
it doesn't matter whether they are public or protected, field access instructions are class bound, and the nearest field in the class hierarchy tree wins. I will change field name, but in fact it's a bug in somebody's class transformer.

**Comment by Archengius** [comment]
changed name
