### ISSUE TITLE
Crash after updating

### ISSUE THREAD

**Issue by MechanosG** [GregTechCE/GregTech#628]
After updating to 1.6.2.189 I've started randomly getting this crash during world gen.  Although there's a chance it might be something OTG did, as I just added it for testing and was using a customized vanilla world gen preset previously.

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2019-03-11 16:35:11 PDT
Description: Exception ticking world

java.lang.IllegalArgumentException: Couldn't find fluid block in a vein!
    at gregtech.api.worldgen.populator.FluidSpringPopulator.lambda$getBlockByIndex$2(FluidSpringPopulator.java:55)
    at java.util.Optional.orElseThrow(Unknown Source)
    at gregtech.api.worldgen.populator.FluidSpringPopulator.getBlockByIndex(FluidSpringPopulator.java:55)
    at gregtech.api.worldgen.generator.CachedGridEntry$ChunkDataEntry.populateChunk(CachedGridEntry.java:324)
    at gregtech.api.worldgen.generator.CachedGridEntry.populateChunk(CachedGridEntry.java:169)
    at gregtech.api.worldgen.generator.WorldGeneratorImpl.generateInternal(WorldGeneratorImpl.java:49)
    at gregtech.api.worldgen.generator.WorldGeneratorImpl.generate(WorldGeneratorImpl.java:40)
    at net.hycrafthd.worldgenerationprofiler.generation.CustomWorldGenerator.generate(CustomWorldGenerator.java:25)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:156)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:985)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:147)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```

[Full Crash Log](https://github.com/GregTechCE/GregTech/files/2954596/crash-2019-03-11_16.35.11-server.txt)

**Comment by alfuken** [comment]
+1 , having the same issue when using OTG

**Comment by CelestialPhoenix** [comment]
There is a fresh update for GTCE- try that first.
 If you still have issues, then as a temporary fix:
Go to .minecraft/config/gregtech/worldgen/overworld and remove heavy_oil
(store it somewhere that isn't in the config folder).

**Comment by MechanosG** [comment]
Downgrading to 1.5.21.182 also temp fixes it without having to make any oil/fluid changes.
