### ISSUE TITLE
Problems of changing recipes of distillery

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#637]
Here is  the script I wrote. (CrafTweaker 2) I want to make it compatible with IC2 biomass to reduce the difficulty for the beginners.
```
import mods.gregtech.recipe.RecipeMaps;

val distillery = mods.gregtech.recipe.RecipeMap.getByName("distillery");
distillery.recipeBuilder()
    .inputs()
	.fluidInputs([<liquid:ic2biomass> * 150])
    .fluidOutputs	([<liquid:ethanol> * 10])
    .property("circuit", 0) //the circult should be set mode 0
    .duration(5)
    .EUt(16)
    .buildAndRegister();
```

However, it doesn't work and the log shows the follows:
```
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: Gregtech\CraftingRecipe.zs}
[INITIALIZATION][CLIENT][ERROR] Gregtech\CraftingRecipe.zs:4 > a method available but none matches the parameters ()
This is usually an error in your script, not in the mod
inputs(ZenTypeNative: crafttweaker.item.IIngredient[])
[INITIALIZATION][CLIENT][ERROR] Gregtech\CraftingRecipe.zs:4 > any values not yet supported
[INITIALIZATION][CLIENT][ERROR] Gregtech\CraftingRecipe.zs:4 > any values not yet supported
[INITIALIZATION][CLIENT][ERROR] Gregtech\CraftingRecipe.zs:4 > any values not yet supported
[INITIALIZATION][CLIENT][ERROR] Gregtech\CraftingRecipe.zs:4 > any values not yet supported
[INITIALIZATION][CLIENT][ERROR] Gregtech\CraftingRecipe.zs:4 > any values not yet supported
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: Gregtech\CraftingRecipe.zs}: null
java.lang.NullPointerException
	at Gregtech\CraftingRecipe.__script__(Gregtech\CraftingRecipe.zs:4)
	at __ZenMain__.run(Gregtech\CraftingRecipe)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:221)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:101)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_141_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:814)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:624)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: Minecraft\CraftingRecipes.zs}
[INITIALIZATION][CLIENT][INFO] loading...
[INITIALIZATION][CLIENT][INFO] load compeleted.
[INITIALIZATION][CLIENT][INFO] Completed script loading in: 403ms
```
I am confused about the configuration of adding recipes to the distillery. 
Reference:
[https://crafttweaker.readthedocs.io/en/latest/#Mods/GregTechCE/Machines/](url)

**Comment by Archengius** [comment]
inputs has signature inputs(IIngredient[]), and you didn't provide any arguments.

**Comment by 15103875d** [comment]
Many thanks.
Could you tell me if I want to modify the recipe?
Because it may not correct to follow the guide.

```
import mods.gregtech.recipe.RecipeMaps;

val distillery = mods.gregtech.recipe.RecipeMap.getByName("distillery");


val distillery_recipe as RecipeMap = RecipeMap.getByName("distillery");
val old = distillery_recipe.findRecipe(16, [], [<liquid:ic2biomass> * 150]);
if(old != null){
	old.remove();
}

distillery.recipeBuilder()
    .inputs([])
	.fluidInputs([<liquid:ic2biomass> * 150])
	.outputs([])
    .fluidOutputs	([<liquid:ethanol> * 10])
    .property("circuit", 0)
    .duration(20)
    .EUt(16)
    .buildAndRegister();
```
