### ISSUE TITLE
Crafting removed? Integrated circuit (#5720/32766)

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#660]
The version of the mod is 1.6.2.191. I found I cannot craft this circuit.

![2019-03-19_00 35 04](https://user-images.githubusercontent.com/43509783/54546548-e2e90480-49de-11e9-9a1f-4e318f5ccd60.png)

I used to use that to transfer oil to Refinery gas. Is this way still available in v1.6?‘

By the way, the cables also require this kind of circuit for crafting. Is that a bug or the configuration of my own server?

Please check the following logs.
After 05:47:00, the extra chests (steel, copper) in Gregtech became invisible. 
The similar problem was indicated in #655 as well. 
```
[04:02:54] [Netty Epoll Server IO #2/INFO] [FML]: Client protocol version 2
[04:02:54] [Netty Epoll Server IO #2/INFO] [FML]: Client attempting to join with 23 mods : minecraft@1.12.2,tconstruct@1.12.2-2.10.1.87,ctgui@1.0.0,FML@8.0.99.99,crafttweakerjei@2.0.2,theoneprobe@1.4.28,microblockcbe@2.6.0.79,inventorytweaks@1.63+release.109.220f184,mycommands@1.12.2-01,harvestcraft@1.12.2zb,minecraftmultipartcbe@2.6.0.79,forgemultipartcbe@2.6.0.79,waila@1.8.26,jei@4.14.4.264,crafttweaker@4.1.14,forge@14.23.5.2807,codechickenlib@3.2.2.353,gregtech@1.6.2.191,ic2@2.8.101-ex112,mantle@1.12-1.3.3.39,mcp@9.42,ironchest@1.12.2-7.0.59.842,journeymap@1.12.2-5.5.4
[04:02:54] [Netty Epoll Server IO #2/INFO] [journeymap]: CLIENT
[04:02:54] [Netty Epoll Server IO #2/INFO] [CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config.
[04:02:56] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[04:02:56] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: yhz[/138.19.255.164:7909] logged in with entity id 713398 at (-43.85255388226081, 64.875, 86.69527900617037)
[04:02:56] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: yhz joined the game
[04:02:56] [Server thread/INFO] [journeymap]: yhz joining dimension 0
[04:02:56] [Server thread/INFO] [journeymap]: Sending log in packet.
[04:24:29] [Server thread/INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@5e333ead)
[04:24:29] [Server thread/INFO] [journeymap]: yhz joining dimension -1
[04:24:52] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:922) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1349) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[04:27:36] [Server thread/INFO] [journeymap]: yhz joining dimension 0
[04:27:38] [Server thread/INFO] [FML]: Unloading dimension -1
[04:47:31] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: yhz lost connection: Disconnected
[04:47:31] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: yhz left the game
[05:30:57] [Netty Epoll Server IO #1/INFO] [FML]: Client protocol version 2
[05:30:57] [Netty Epoll Server IO #1/INFO] [FML]: Client attempting to join with 23 mods : minecraft@1.12.2,tconstruct@1.12.2-2.10.1.87,ctgui@1.0.0,FML@8.0.99.99,crafttweakerjei@2.0.2,theoneprobe@1.4.28,microblockcbe@2.6.0.79,inventorytweaks@1.63+release.109.220f184,mycommands@1.12.2-01,harvestcraft@1.12.2zb,minecraftmultipartcbe@2.6.0.79,forgemultipartcbe@2.6.0.79,waila@1.8.26,jei@4.14.4.264,crafttweaker@4.1.14,forge@14.23.5.2807,codechickenlib@3.2.2.353,gregtech@1.6.2.191,ic2@2.8.101-ex112,mantle@1.12-1.3.3.39,mcp@9.42,ironchest@1.12.2-7.0.59.842,journeymap@1.12.2-5.5.4
[05:30:57] [Netty Epoll Server IO #1/INFO] [journeymap]: CLIENT
[05:30:57] [Netty Epoll Server IO #1/INFO] [CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config.
[05:30:59] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[05:30:59] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: yhz[/138.19.255.164:9126] logged in with entity id 755323 at (212.70550737054467, 16.0, 73.1853458857327)
[05:30:59] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: yhz joined the game
[05:30:59] [Server thread/INFO] [journeymap]: yhz joining dimension 0
[05:30:59] [Server thread/INFO] [journeymap]: Sending log in packet.
[05:45:33] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:922) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1349) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[05:45:33] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:922) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1349) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[05:45:33] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:922) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1349) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[05:45:33] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:922) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1349) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[05:45:34] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:922) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1349) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
	at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[05:47:57] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: yhz lost connection: Disconnected
[05:47:57] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: yhz left the game
[07:16:37] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Stopping the server
[07:16:37] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[07:16:37] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[07:16:37] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[07:16:37] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
[07:16:37] [Server thread/INFO] [FML]: Unloading dimension 0
[07:16:37] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[07:16:37] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[07:16:37] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
```

**Comment by ProxyPlayerHD** [comment]
yep, the Integrated circuit has no recipe for some reason, i had to cheat some in to get actual process in the mod

also noticed that you cannot take liquids out of some machines, like the assembler, no matter what liquid container i used, or what i clicked i was unable to remove the liquid from it.

**Comment by 15103875d** [comment]
So is there any other ways for craft the cables? That is necessary for crafting machines...
