### ISSUE TITLE
[Crash] The client crash when using the magnetizing machine

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#700]
Gregtech version: 1.6.9.382
The crash occurs under the following conditions:
(1) Holding a WRENCH;
(2) Adding IRON INGOT to the magnetizing machine

When two conditions are satisfied, the client crashed instantly.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 4/2/19 3:36 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at gregtech.common.render.WrenchOverlayRenderer.shouldDrawOverlayForItem(WrenchOverlayRenderer.java:84)
	at gregtech.common.render.WrenchOverlayRenderer.onDrawBlockHighlight(WrenchOverlayRenderer.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_WrenchOverlayRenderer_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1361)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gregtech.common.render.WrenchOverlayRenderer.shouldDrawOverlayForItem(WrenchOverlayRenderer.java:84)
	at gregtech.common.render.WrenchOverlayRenderer.onDrawBlockHighlight(WrenchOverlayRenderer.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_WrenchOverlayRenderer_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1361)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['yhz'/48879, l='MpServer', x=-70.97, y=65.50, z=100.73]]
	Chunk stats: MultiplayerChunkCache: 211, 211
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-64,64,232), Chunk: (at 0,4,8 in -4,14; contains blocks -64,0,224 to -49,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 106657927 game time, 69941639 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 206 total; [EntityPlayerSP['yhz'/48879, l='MpServer', x=-70.97, y=65.50, z=100.73], EntityBat['蝙蝠'/43055, l='MpServer', x=-51.48, y=33.10, z=110.13], EntitySheep['羊'/77, l='MpServer', x=-150.45, y=63.00, z=102.12], EntityCow['牛'/78, l='MpServer', x=-150.55, y=67.00, z=110.55], EntitySheep['羊'/79, l='MpServer', x=-142.45, y=66.00, z=106.13], EntityCow['牛'/82, l='MpServer', x=-150.63, y=68.00, z=117.57], EntitySheep['羊'/87, l='MpServer', x=-150.55, y=69.00, z=140.50], EntitySheep['羊'/88, l='MpServer', x=-148.77, y=74.00, z=129.52], EntityCow['牛'/89, l='MpServer', x=-149.50, y=70.00, z=140.50], EntitySheep['羊'/90, l='MpServer', x=-144.45, y=73.00, z=133.45], EntitySheep['羊'/91, l='MpServer', x=-145.55, y=73.00, z=131.49], EntityCow['牛'/92, l='MpServer', x=-145.28, y=72.00, z=129.42], EntitySheep['羊'/93, l='MpServer', x=-145.45, y=73.00, z=136.20], EntitySheep['羊'/94, l='MpServer', x=-145.43, y=73.00, z=133.55], EntityCow['牛'/98, l='MpServer', x=-144.55, y=60.00, z=147.55], EntitySheep['羊'/111, l='MpServer', x=-130.74, y=66.00, z=116.50], EntityCow['牛'/112, l='MpServer', x=-128.82, y=65.00, z=103.48], EntitySheep['羊'/113, l='MpServer', x=-136.74, y=66.00, z=114.41], EntitySheep['羊'/115, l='MpServer', x=-139.53, y=67.00, z=120.52], EntityCow['牛'/116, l='MpServer', x=-143.45, y=64.00, z=119.51], EntityCow['牛'/117, l='MpServer', x=-128.14, y=65.00, z=112.25], EntityCow['牛'/118, l='MpServer', x=-131.42, y=68.00, z=123.78], EntityCow['牛'/119, l='MpServer', x=-138.68, y=72.00, z=129.60], EntityCow['牛'/120, l='MpServer', x=-141.75, y=71.00, z=141.45], EntityCow['牛'/121, l='MpServer', x=-137.29, y=71.00, z=128.75], EntityCow['牛'/122, l='MpServer', x=-138.55, y=70.00, z=142.45], EntitySheep['羊'/123, l='MpServer', x=-130.41, y=68.00, z=132.74], EntitySheep['羊'/124, l='MpServer', x=-136.64, y=71.00, z=132.37], EntitySheep['羊'/125, l='MpServer', x=-143.55, y=73.00, z=132.55], EntityCow['牛'/126, l='MpServer', x=-140.55, y=71.00, z=132.45], EntityCow['牛'/127, l='MpServer', x=-143.28, y=60.00, z=144.45], EntityCow['牛'/128, l='MpServer', x=-136.55, y=69.00, z=147.45], EntityZombie['僵尸'/47744, l='MpServer', x=-23.20, y=64.00, z=126.60], EntitySheep['羊'/129, l='MpServer', x=-131.83, y=68.00, z=148.73], EntitySheep['羊'/130, l='MpServer', x=-141.19, y=71.00, z=166.43], EntitySheep['羊'/131, l='MpServer', x=-143.45, y=72.00, z=144.45], EntityCow['牛'/134, l='MpServer', x=-134.18, y=70.00, z=163.28], EntitySheep['羊'/135, l='MpServer', x=-140.48, y=71.00, z=161.25], EntityCow['牛'/141, l='MpServer', x=-130.55, y=71.00, z=175.77], EntityEnderman['末影人'/47760, l='MpServer', x=-137.50, y=66.00, z=104.50], EntityEnderman['末影人'/47761, l='MpServer', x=-141.50, y=66.00, z=103.50], EntityCow['牛'/148, l='MpServer', x=-123.13, y=64.00, z=99.14], EntityCow['牛'/149, l='MpServer', x=-123.55, y=65.00, z=125.45], EntitySheep['羊'/150, l='MpServer', x=-127.17, y=65.00, z=112.70], EntitySheep['羊'/152, l='MpServer', x=-121.55, y=65.00, z=139.45], EntitySheep['羊'/153, l='MpServer', x=-125.27, y=67.00, z=128.48], EntitySheep['羊'/154, l='MpServer', x=-117.19, y=64.00, z=137.44], EntitySheep['羊'/155, l='MpServer', x=-117.55, y=64.00, z=141.75], EntitySheep['羊'/156, l='MpServer', x=-119.50, y=64.00, z=136.25], EntityCow['牛'/157, l='MpServer', x=-118.42, y=66.00, z=157.20], EntityCow['牛'/158, l='MpServer', x=-113.53, y=65.00, z=159.15], EntityCow['牛'/159, l='MpServer', x=-124.45, y=66.00, z=148.43], EntitySheep['羊'/160, l='MpServer', x=-123.23, y=68.00, z=161.48], EntityCow['牛'/161, l='MpServer', x=-126.47, y=67.00, z=152.55], EntityCow['牛'/162, l='MpServer', x=-118.22, y=64.00, z=145.45], EntitySheep['羊'/163, l='MpServer', x=-124.27, y=68.00, z=156.20], EntitySheep['羊'/164, l='MpServer', x=-119.38, y=67.00, z=157.78], EntitySheep['羊'/167, l='MpServer', x=-121.52, y=68.00, z=164.73], EntityCow['牛'/168, l='MpServer', x=-123.87, y=69.00, z=167.11], EntityPig['猪'/169, l='MpServer', x=-127.50, y=69.00, z=160.30], EntityCow['牛'/172, l='MpServer', x=-114.78, y=70.00, z=180.45], EntitySheep['羊'/197, l='MpServer', x=-94.48, y=64.00, z=125.05], EntityCow['牛'/198, l='MpServer', x=-99.86, y=64.00, z=120.48], EntityCow['牛'/199, l='MpServer', x=-98.42, y=64.00, z=123.44], EntitySheep['羊'/200, l='MpServer', x=-93.76, y=64.00, z=123.11], EntitySheep['羊'/201, l='MpServer', x=-97.57, y=64.00, z=124.16], EntitySheep['羊'/202, l='MpServer', x=-97.99, y=64.00, z=120.51], EntityCow['牛'/203, l='MpServer', x=-99.01, y=64.00, z=119.78], EntitySheep['羊'/204, l='MpServer', x=-94.78, y=64.00, z=127.97], EntityCow['牛'/205, l='MpServer', x=-96.28, y=64.00, z=122.20], EntityCow['牛'/206, l='MpServer', x=-100.93, y=64.00, z=123.26], EntitySheep['羊'/207, l='MpServer', x=-94.74, y=64.00, z=126.93], EntityCow['牛'/208, l='MpServer', x=-97.70, y=64.00, z=127.94], EntitySheep['羊'/209, l='MpServer', x=-92.81, y=64.00, z=127.96], EntitySheep['羊'/210, l='MpServer', x=-97.68, y=64.00, z=125.08], EntityCow['牛'/211, l='MpServer', x=-95.28, y=64.00, z=121.65], EntitySheep['羊'/212, l='MpServer', x=-100.93, y=64.00, z=112.77], EntitySheep['羊'/213, l='MpServer', x=-90.12, y=64.00, z=126.82], EntitySheep['羊'/214, l='MpServer', x=-90.95, y=64.00, z=128.02], EntitySheep['羊'/215, l='MpServer', x=-99.74, y=64.00, z=126.10], EntitySheep['羊'/216, l='MpServer', x=-100.93, y=64.00, z=120.80], EntitySheep['羊'/217, l='MpServer', x=-91.01, y=64.00, z=128.93], EntitySheep['羊'/218, l='MpServer', x=-100.93, y=64.00, z=124.16], EntityCow['牛'/219, l='MpServer', x=-98.79, y=64.00, z=124.39], EntitySheep['羊'/220, l='MpServer', x=-100.93, y=64.00, z=127.93], EntityCow['牛'/221, l='MpServer', x=-90.87, y=64.00, z=124.12], EntityCow['牛'/222, l='MpServer', x=-97.81, y=64.00, z=119.56], EntityCow['牛'/223, l='MpServer', x=-95.45, y=64.00, z=124.22], EntitySheep['羊'/224, l='MpServer', x=-99.66, y=64.00, z=117.66], EntitySkeleton['骷髅'/47841, l='MpServer', x=-148.50, y=67.00, z=116.50], EntitySheep['羊'/225, l='MpServer', x=-100.93, y=64.00, z=125.11], EntityCow['牛'/226, l='MpServer', x=-89.51, y=64.00, z=110.88], EntitySheep['羊'/227, l='MpServer', x=-100.93, y=64.00, z=126.99], EntityCow['牛'/228, l='MpServer', x=-99.98, y=64.00, z=118.65], EntitySheep['羊'/229, l='MpServer', x=-99.25, y=64.00, z=112.69], EntityCow['牛'/230, l='MpServer', x=-89.07, y=64.00, z=127.84], EntityCow['牛'/231, l='MpServer', x=-94.16, y=64.00, z=111.70], EntitySheep['羊'/232, l='MpServer', x=-94.13, y=64.00, z=119.46], EntitySheep['羊'/233, l='MpServer', x=-89.84, y=64.00, z=120.93], EntitySheep['羊'/234, l='MpServer', x=-100.93, y=64.00, z=126.06], EntityCow['牛'/235, l='MpServer', x=-92.00, y=64.00, z=126.39], EntitySheep['羊'/236, l='MpServer', x=-96.74, y=64.00, z=127.09], EntityCow['牛'/237, l='MpServer', x=-94.82, y=64.00, z=130.53], EntitySheep['羊'/238, l='MpServer', x=-100.93, y=64.00, z=128.93], EntitySheep['羊'/239, l='MpServer', x=-108.19, y=64.00, z=131.50], EntitySheep['羊'/240, l='MpServer', x=-97.07, y=64.00, z=129.84], EntityCow['牛'/241, l='MpServer', x=-98.89, y=64.00, z=128.93], EntityCow['牛'/242, l='MpServer', x=-96.74, y=64.00, z=128.93], EntityCow['牛'/243, l='MpServer', x=-95.76, y=64.00, z=128.93], EntitySheep['羊'/244, l='MpServer', x=-103.19, y=64.00, z=130.51], EntitySheep['羊'/245, l='MpServer', x=-94.71, y=64.00, z=128.93], EntityCow['牛'/246, l='MpServer', x=-86.63, y=65.00, z=135.55], EntitySheep['羊'/247, l='MpServer', x=-96.49, y=66.00, z=139.21], EntitySheep['羊'/249, l='MpServer', x=-104.22, y=65.00, z=162.44], EntityCow['牛'/250, l='MpServer', x=-108.19, y=64.00, z=153.50], EntitySheep['羊'/251, l='MpServer', x=-99.19, y=65.00, z=154.62], EntitySheep['羊'/252, l='MpServer', x=-118.45, y=65.00, z=150.76], EntitySheep['羊'/253, l='MpServer', x=-98.54, y=65.00, z=153.27], EntitySheep['羊'/254, l='MpServer', x=-107.77, y=65.00, z=157.52], EntityCow['牛'/255, l='MpServer', x=-111.53, y=66.00, z=165.44], EntityPig['猪'/256, l='MpServer', x=-105.51, y=67.00, z=172.78], EntityCow['牛'/257, l='MpServer', x=-108.51, y=68.00, z=175.94], EntityCow['牛'/276, l='MpServer', x=-95.72, y=64.00, z=126.78], EntitySheep['羊'/277, l='MpServer', x=-100.93, y=64.00, z=115.60], EntitySheep['羊'/278, l='MpServer', x=-92.90, y=64.00, z=128.93], EntitySheep['羊'/279, l='MpServer', x=-98.89, y=64.00, z=122.01], EntityCow['牛'/280, l='MpServer', x=-100.93, y=64.00, z=122.16], EntitySquid['鱿鱼'/47384, l='MpServer', x=-13.21, y=60.24, z=117.04], EntitySheep['羊'/281, l='MpServer', x=-99.92, y=64.00, z=125.13], EntitySquid['鱿鱼'/47385, l='MpServer', x=-13.66, y=61.01, z=121.42], EntitySheep['羊'/282, l='MpServer', x=-99.44, y=64.00, z=123.21], EntitySquid['鱿鱼'/47386, l='MpServer', x=-15.60, y=59.20, z=120.39], EntityCow['牛'/283, l='MpServer', x=-96.41, y=64.00, z=125.16], EntitySheep['羊'/284, l='MpServer', x=-97.58, y=64.00, z=118.57], EntitySheep['羊'/285, l='MpServer', x=-94.44, y=64.00, z=125.98], EntityCow['牛'/286, l='MpServer', x=-90.03, y=64.00, z=128.01], EntitySheep['羊'/287, l='MpServer', x=-94.73, y=64.00, z=122.69], EntityCow['牛'/288, l='MpServer', x=-91.90, y=64.00, z=127.94], EntityCow['牛'/289, l='MpServer', x=-92.96, y=64.00, z=125.99], EntityCow['牛'/290, l='MpServer', x=-90.07, y=64.00, z=128.93], EntityCow['牛'/291, l='MpServer', x=-89.07, y=64.00, z=128.93], EntitySheep['羊'/292, l='MpServer', x=-92.00, y=64.00, z=128.93], EntityCow['牛'/293, l='MpServer', x=-97.86, y=64.00, z=122.41], EntitySheep['羊'/294, l='MpServer', x=-95.73, y=64.00, z=123.13], EntitySheep['羊'/295, l='MpServer', x=-98.70, y=64.00, z=127.91], EntitySheep['羊'/296, l='MpServer', x=-100.93, y=64.00, z=114.70], EntitySheep['羊'/297, l='MpServer', x=-91.07, y=64.00, z=127.03], EntityCow['牛'/298, l='MpServer', x=-97.63, y=64.00, z=126.10], EntityCow['牛'/299, l='MpServer', x=-99.62, y=64.00, z=114.75], EntitySheep['羊'/300, l='MpServer', x=-95.45, y=64.00, z=125.75], EntitySheep['羊'/301, l='MpServer', x=-97.65, y=64.00, z=128.93], EntitySheep['羊'/302, l='MpServer', x=-99.49, y=64.00, z=115.72], EntitySheep['羊'/303, l='MpServer', x=-99.83, y=64.00, z=122.28], EntitySheep['羊'/304, l='MpServer', x=-96.68, y=64.00, z=127.99], EntitySheep['羊'/305, l='MpServer', x=-98.64, y=64.00, z=125.27], EntitySheep['羊'/306, l='MpServer', x=-100.01, y=64.00, z=124.21], EntitySheep['羊'/307, l='MpServer', x=-96.63, y=64.00, z=126.20], EntityCow['牛'/308, l='MpServer', x=-100.93, y=64.00, z=118.60], EntityCow['牛'/309, l='MpServer', x=-99.70, y=64.00, z=128.02], EntitySheep['羊'/310, l='MpServer', x=-99.97, y=64.00, z=128.93], EntitySheep['羊'/311, l='MpServer', x=-98.89, y=64.00, z=113.57], EntitySheep['羊'/312, l='MpServer', x=-95.73, y=64.00, z=127.87], EntityCow['牛'/313, l='MpServer', x=-93.73, y=64.00, z=127.97], EntityCow['牛'/314, l='MpServer', x=-100.93, y=64.00, z=117.56], EntitySheep['羊'/315, l='MpServer', x=-97.08, y=64.00, z=121.17], EntityCow['牛'/316, l='MpServer', x=-93.41, y=64.00, z=125.03], EntitySheep['羊'/317, l='MpServer', x=-92.26, y=64.00, z=124.96], EntitySheep['羊'/318, l='MpServer', x=-98.89, y=64.00, z=120.88], EntityCow['牛'/319, l='MpServer', x=-94.10, y=64.00, z=124.00], EntitySheep['羊'/320, l='MpServer', x=-96.76, y=64.00, z=123.16], EntitySheep['羊'/321, l='MpServer', x=-99.99, y=64.00, z=121.38], EntitySheep['羊'/322, l='MpServer', x=-96.43, y=64.00, z=124.13], EntitySheep['羊'/323, l='MpServer', x=-100.93, y=64.00, z=116.65], EntitySheep['羊'/324, l='MpServer', x=-93.76, y=64.00, z=126.96], EntityCow['牛'/325, l='MpServer', x=-100.93, y=64.00, z=119.51], EntitySheep['羊'/326, l='MpServer', x=-100.93, y=64.00, z=113.67], EntitySheep['羊'/327, l='MpServer', x=-99.90, y=64.00, z=116.63], EntityCow['牛'/328, l='MpServer', x=-94.28, y=64.00, z=121.18], EntitySheep['羊'/329, l='MpServer', x=-99.89, y=64.00, z=127.08], EntityCow['牛'/330, l='MpServer', x=-93.81, y=64.00, z=128.93], EntitySheep['羊'/331, l='MpServer', x=-96.08, y=64.00, z=120.70], EntitySheep['羊'/332, l='MpServer', x=-95.20, y=66.00, z=141.42], EntityCow['牛'/333, l='MpServer', x=-97.67, y=64.00, z=127.09], EntityCow['牛'/334, l='MpServer', x=-87.61, y=65.00, z=135.18], EntityCow['牛'/335, l='MpServer', x=-98.68, y=64.00, z=127.15], EntityCow['牛'/336, l='MpServer', x=-90.87, y=64.00, z=118.93], EntitySheep['羊'/337, l='MpServer', x=-85.74, y=66.00, z=161.55], EntitySheep['羊'/338, l='MpServer', x=-95.51, y=65.00, z=155.26], EntityCow['牛'/340, l='MpServer', x=-86.84, y=67.00, z=173.62], EntitySheep['羊'/341, l='MpServer', x=-93.30, y=66.00, z=167.29], EntitySheep['羊'/342, l='MpServer', x=-91.45, y=66.00, z=170.15], EntitySheep['羊'/363, l='MpServer', x=-63.54, y=68.00, z=161.29], EntitySheep['羊'/365, l='MpServer', x=-71.79, y=69.00, z=161.72], EntitySheep['羊'/368, l='MpServer', x=-78.30, y=69.00, z=178.50], EntityCow['牛'/369, l='MpServer', x=-70.55, y=68.00, z=177.45], EntityCow['牛'/370, l='MpServer', x=-78.43, y=68.00, z=176.22], EntitySheep['羊'/371, l='MpServer', x=-65.48, y=68.00, z=180.73], EntitySheep['羊'/386, l='MpServer', x=-56.08, y=67.00, z=144.77], EntityCow['牛'/387, l='MpServer', x=-61.23, y=67.00, z=167.57], EntitySheep['羊'/388, l='MpServer', x=-58.79, y=66.00, z=178.83], EntitySpider['蜘蛛'/47500, l='MpServer', x=-133.50, y=66.00, z=109.50], EntitySheep['羊'/415, l='MpServer', x=-26.35, y=70.00, z=149.22], EntitySheep['羊'/416, l='MpServer', x=-17.19, y=69.00, z=162.63], EntityCow['牛'/433, l='MpServer', x=-5.84, y=68.00, z=153.61], EntityChicken['鸡'/434, l='MpServer', x=-7.88, y=65.00, z=170.52], EntitySheep['羊'/435, l='MpServer', x=3.22, y=64.00, z=159.59]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3018537856 bytes (2878 MB) / 4093640704 bytes (3904 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2807 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                        | Signature                                |
	|:------ |:--------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2807.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2807             | forge-1.12.2-14.23.5.2807.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | codechickenlib        | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | crafttweaker          | 4.1.14                   | CraftTweaker2-1.12-4.1.14.jar                 | None                                     |
	| LCHIJA | ctgui                 | 1.0.0                    | CraftTweaker2-1.12-4.1.14.jar                 | None                                     |
	| LCHIJA | jei                   | 4.14.4.264               | jei_1.12.2-4.14.4.264.jar                     | None                                     |
	| LCHIJA | crafttweakerjei       | 2.0.2                    | CraftTweaker2-1.12-4.1.14.jar                 | None                                     |
	| LCHIJA | forgemultipartcbe     | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe         | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | None                                     |
	| LCHIJA | minecraftmultipartcbe | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | None                                     |
	| LCHIJA | gregtech              | 1.6.9.382                | gregtech-1.12.2-1.6.9.382.jar                 | None                                     |
	| LCHIJA | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | ic2                   | 2.8.101-ex112            | industrialcraft-2-2.8.101-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest             | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar               | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                   | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                      | None                                     |
	| LCHIJA | mycommands            | 1.12.2-01                | MyCommands-1.12.2-01.jar                      | None                                     |
	| LCHIJA | harvestcraft          | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zb.jar               | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar               | None                                     |
	| LCHIJA | theoneprobe           | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                   | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce MX150/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Launched Version: HMCL 3.2.112
	LWJGL: 2.9.4
	OpenGL: GeForce MX150/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
```

**Comment by Firew0lf** [comment]
I got the exact same crash while holding a pipe (from Exponentialistics Pipes) and looking at a machine...
Maybe adding a null check [here](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/common/render/WrenchOverlayRenderer.java#L84) could solve it ?

**Comment by Takakura-Anri** [comment]
They should have added `if (metaItem.getItem(itemStack) != null)`.

**Comment by ProsperCraft** [comment]
Holding anything near a machine crashes you.
