### ISSUE TITLE
[Crash] Crash on a loop when placing redstone on a machine

### ISSUE THREAD

**Issue by thinseal** [GregTechCE/GregTech#757]
Crash when placing a redstone on a machine, and repeated crash when trying to get close to the area.

```
----------Crash Report-----------
java.lang.NullPointerException: Unexpected error
	at gregtech.api.metatileentity.MetaTileEntity.getCoverAtSide(MetaTileEntity.java:346)
	at gregtech.api.metatileentity.MetaTileEntity.canConnectRedstone(MetaTileEntity.java:448)
	at gregtech.api.block.machines.BlockMachine.canConnectRedstone(BlockMachine.java:294)
	at net.minecraft.block.BlockRedstoneWire.canConnectTo(BlockRedstoneWire.java:456)
	at net.minecraft.block.BlockRedstoneWire.func_176340_e(BlockRedstoneWire.java:434)
	at net.minecraft.block.BlockRedstoneWire.func_176341_c(BlockRedstoneWire.java:102)
	at net.minecraft.block.BlockRedstoneWire.func_176221_a(BlockRedstoneWire.java:91)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:427)
	at net.minecraft.block.BlockRedstoneWire.func_185496_a(BlockRedstoneWire.java:54)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:468)
	at net.minecraft.block.Block.func_180636_a(Block.java:631)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:473)
	at net.minecraft.world.World.func_147447_a(World.java:1086)
	at net.minecraft.world.World.func_72901_a(World.java:929)
	at mcp.mobius.waila.overlay.RayTracing.rayTrace(RayTracing.java:83)
	at mcp.mobius.waila.overlay.RayTracing.fire(RayTracing.java:50)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_228_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1707)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gregtech.api.metatileentity.MetaTileEntity.getCoverAtSide(MetaTileEntity.java:346)
	at gregtech.api.metatileentity.MetaTileEntity.canConnectRedstone(MetaTileEntity.java:448)
	at gregtech.api.block.machines.BlockMachine.canConnectRedstone(BlockMachine.java:294)
	at net.minecraft.block.BlockRedstoneWire.canConnectTo(BlockRedstoneWire.java:456)
	at net.minecraft.block.BlockRedstoneWire.func_176340_e(BlockRedstoneWire.java:434)
	at net.minecraft.block.BlockRedstoneWire.func_176341_c(BlockRedstoneWire.java:102)
	at net.minecraft.block.BlockRedstoneWire.func_176221_a(BlockRedstoneWire.java:91)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:427)
	at net.minecraft.block.BlockRedstoneWire.func_185496_a(BlockRedstoneWire.java:54)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:468)
	at net.minecraft.block.Block.func_180636_a(Block.java:631)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:473)
	at net.minecraft.world.World.func_147447_a(World.java:1086)
	at net.minecraft.world.World.func_72901_a(World.java:929)
	at mcp.mobius.waila.overlay.RayTracing.rayTrace(RayTracing.java:83)
	at mcp.mobius.waila.overlay.RayTracing.fire(RayTracing.java:50)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_228_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['thinseal'/3928, l='MpServer', x=171.99, y=77.42, z=125.38]]
	Chunk stats: MultiplayerChunkCache: 137, 137
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (65,80,241), Chunk: (at 1,5,1 in 4,15; contains blocks 64,0,240 to 79,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 7248284 game time, 5847230 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 16 total; [EntitySpider['蜘蛛'/128, l='MpServer', x=110.50, y=14.00, z=114.50], EntityItem['item.item.arrow'/193, l='MpServer', x=189.61, y=80.00, z=183.62], EntityItem['item.item.bone'/194, l='MpServer', x=191.14, y=80.00, z=184.57], EntityZombie['僵尸'/164, l='MpServer', x=154.50, y=37.00, z=128.50], EntitySquid['鱿鱼'/645, l='MpServer', x=131.50, y=62.00, z=134.50], EntitySquid['鱿鱼'/646, l='MpServer', x=131.50, y=62.00, z=135.50], EntitySquid['鱿鱼'/647, l='MpServer', x=128.50, y=62.00, z=135.50], EntitySquid['鱿鱼'/648, l='MpServer', x=130.50, y=62.00, z=132.50], EntitySpider['蜘蛛'/142, l='MpServer', x=113.50, y=14.00, z=117.50], EntityZombie['僵尸'/1137, l='MpServer', x=188.77, y=58.00, z=138.50], EntityPlayerSP['thinseal'/3928, l='MpServer', x=171.99, y=77.42, z=125.38], EntitySpider['蜘蛛'/180, l='MpServer', x=180.76, y=58.00, z=136.70], EntityZombie['僵尸'/662, l='MpServer', x=158.50, y=20.00, z=168.50], EntityItem['item.item.arrow'/857, l='MpServer', x=126.19, y=68.00, z=179.80], EntityItem['item.item.rottenFlesh'/157, l='MpServer', x=128.35, y=72.00, z=126.58], EntityCreeper['爬行者'/830, l='MpServer', x=124.50, y=16.00, z=156.50]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.13-SNAPSHOT:52bc4fe:273) <- fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1874396096 bytes (1787 MB) / 2768240640 bytes (2640 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2759 Optifine OptiFine_1.12.2_HD_U_E4_pre1 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version       | Source                                               | Signature                                |
	|:------ |:------------------- |:------------- |:---------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2        | minecraft.jar                                        | None                                     |
	| UCHIJA | mcp                 | 9.42          | minecraft.jar                                        | None                                     |
	| UCHIJA | FML                 | 8.0.99.99     | forge-1.12.2-14.23.4.2759.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.4.2759  | forge-1.12.2-14.23.4.2759.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | wawla               | 2.5.244       | [更多信息显示]Wawla-1.12.2-2.5.244-CN.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | jei                 | 4.15.0.268    | jei_1.12.2-4.15.0.268.jar                            | None                                     |
	| UCHIJA | jeresources         | 0.8.5.26      | [更详细的资源信息]JustEnoughResources-1.12.2-0.8.5.26-CN.jar | None                                     |
	| UCHIJA | wailaharvestability | 1.1.12        | [更详细的采集信息]WailaHarvestability-mc1.12-1.1.12-CN.jar   | None                                     |
	| UCHIJA | neat                | 1.4-15        | [简洁的血条显示]Neat-1.4-15.jar                             | None                                     |
	| UCHIJA | waila               | 1.8.20        | [额外信息显示]Hwyla-1.8.20-B35_1.12_CN.jar                 | None                                     |
	| UCHIJA | buildcraftlib       | 7.99.23       | buildcraft-all-7.99.23.jar                           | None                                     |
	| UCHIJA | buildcraftcore      | 7.99.23       | buildcraft-all-7.99.23.jar                           | None                                     |
	| UCHIJA | buildcraftbuilders  | 7.99.23       | buildcraft-all-7.99.23.jar                           | None                                     |
	| UCHIJA | buildcrafttransport | 7.99.23       | buildcraft-all-7.99.23.jar                           | None                                     |
	| UCHIJA | buildcraftsilicon   | 7.99.23       | buildcraft-all-7.99.23.jar                           | None                                     |
	| UCHIJA | crafttweaker        | 4.1.17        | CraftTweaker2-1.12-4.1.17.jar                        | None                                     |
	| UCHIJA | buildcraftcompat    | 7.99.23       | buildcraft-all-7.99.23.jar                           | None                                     |
	| UCHIJA | buildcraftenergy    | 7.99.23       | buildcraft-all-7.99.23.jar                           | None                                     |
	| UCHIJA | buildcraftfactory   | 7.99.23       | buildcraft-all-7.99.23.jar                           | None                                     |
	| UCHIJA | buildcraftrobotics  | 7.99.23       | buildcraft-all-7.99.23.jar                           | None                                     |
	| UCHIJA | codechickenlib      | 3.2.2.353     | CodeChickenLib-1.12.2-3.2.2.353-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | ctgui               | 1.0.0         | CraftTweaker2-1.12-4.1.17.jar                        | None                                     |
	| UCHIJA | crafttweakerjei     | 2.0.3         | CraftTweaker2-1.12-4.1.17.jar                        | None                                     |
	| UCHIJA | customnpcs          | 1.12          | CustomNPCs_1.12.2(30Jan19).jar                       | None                                     |
	| UCHIJA | gregtech            | 1.7.0.387     | gregtech-1.12.2-1.7.0.387.jar                        | None                                     |
	| UCHIJA | ic2                 | 2.8.112-ex112 | industrialcraft-2-2.8.112-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJA | mtrm                | 1.2.2.30      | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar           | None                                     |
	| UCHIJA | mobends             | 0.24          | mobends-0.24_for_MC-1.12.2.jar                       | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.17' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Launched Version: HMCL 3.2.112
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.17, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: Foglake Resource Pack (incompatible)
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E4_pre1
	OptiFine Build: 20181218-105534
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 419.17
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by thinseal** [comment]
![bug](https://user-images.githubusercontent.com/30489768/56360816-494c8700-6218-11e9-8fb3-68c71ad4fd41.png)
Correction:
Only the redstone in the configuration like this (2 rows of machines, one upper and one lower and 1 redstone on the bottom row) would result in the crash, when looking at the redstone.
