### ISSUE TITLE
StringIndexOutOfBoundsException with CoverOreDictionaryFilter

### ISSUE THREAD

**Issue by Sir-Will** [GregTechCE/GregTech#808]
If the filter is set to `*` it causes the following crash:

gregtech-1.12.2-1.7.0.387
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at gregtech.common.covers.CoverOreDictionaryFilter.oreDictionaryFilterMatch(CoverOreDictionaryFilter.java:186)
	at gregtech.common.covers.CoverOreDictionaryFilter$ItemHandlerOreDictFiltered.insertItem(CoverOreDictionaryFilter.java:148)
	at crazypants.enderio.base.capability.ItemTools.insertItemStacked(ItemTools.java:370)
	at crazypants.enderio.base.capability.ItemTools.doInsertItem(ItemTools.java:194)
	at crazypants.enderio.conduits.conduit.item.NetworkedInventory.insertItem(NetworkedInventory.java:286)
	at crazypants.enderio.conduits.conduit.item.NetworkedInventory.insertIntoTargets(NetworkedInventory.java:231)
	at crazypants.enderio.conduits.conduit.item.NetworkedInventory.doTransfer(NetworkedInventory.java:191)
	at crazypants.enderio.conduits.conduit.item.NetworkedInventory.transferItems(NetworkedInventory.java:174)
	at crazypants.enderio.conduits.conduit.item.NetworkedInventory.onTick(NetworkedInventory.java:111)
	at crazypants.enderio.conduits.conduit.item.ItemConduitNetwork.tickEnd(ItemConduitNetwork.java:152)
	at crazypants.enderio.base.handler.ServerTickHandler.onServerTick(ServerTickHandler.java:57)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_175_ServerTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.lang.String.substring(String.java:1967)
	at gregtech.common.covers.CoverOreDictionaryFilter.oreDictionaryFilterMatch(CoverOreDictionaryFilter.java:186)
	at gregtech.common.covers.CoverOreDictionaryFilter$ItemHandlerOreDictFiltered.insertItem(CoverOreDictionaryFilter.java:148)
	at crazypants.enderio.base.capability.ItemTools.insertItemStacked(ItemTools.java:370)
	at crazypants.enderio.base.capability.ItemTools.doInsertItem(ItemTools.java:194)
	at crazypants.enderio.conduits.conduit.item.NetworkedInventory.insertItem(NetworkedInventory.java:286)
	at crazypants.enderio.conduits.conduit.item.NetworkedInventory.insertIntoTargets(NetworkedInventory.java:231)
	at crazypants.enderio.conduits.conduit.item.NetworkedInventory.doTransfer(NetworkedInventory.java:191)
	at crazypants.enderio.conduits.conduit.item.NetworkedInventory.transferItems(NetworkedInventory.java:174)
	at crazypants.enderio.conduits.conduit.item.NetworkedInventory.onTick(NetworkedInventory.java:111)
	at crazypants.enderio.conduits.conduit.item.ItemConduitNetwork.tickEnd(ItemConduitNetwork.java:152)
	at crazypants.enderio.base.handler.ServerTickHandler.onServerTick(ServerTickHandler.java:57)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_175_ServerTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjo000(MinecraftServer.java:3975)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Cyprex** [comment]
This happens every time I try to load my world due to the ticking tile entity, is there a good way to fix this?

**Comment by BorisMulder** [comment]
+1, It seems to only happen after I place a chest to input from/output to next to the cover.

**Comment by Cyprex** [comment]
Here is the offending line in question: https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/common/covers/CoverOreDictionaryFilter.java#L186
I checked the code but I honestly have no idea why this happens. For a workaround setting your filter to ** or <letter>* might work.
If your world is crashing on load:
1. Backup your world
2. Enable Remove erroring tile entities in forge.cfg. You can do this in-game too, via mod options->minecraft forge, so there is no need to restart the game
3. Load the world, break the offending machine.
4. Leave the world and set remove erroring tile entities in forge.cfg to false again.
Keep in mind that this removes ALL erroring tile entities, and I don't know how strict forge is here, if you're unlucky a large amount of tile entities will be removed by this.
