### ISSUE TITLE
[Crash] Crash on a loop when changing the texts in Ore Dictionary Filter

### ISSUE THREAD

**Issue by thinseal** [GregTechCE/GregTech#822]
How to repeat:
1. Place a Blend-O-Matic, supply power, and put in any ore, and switch on the auto output button
2. Place an Ore Dictionary Filter on the output surface
3. Place a chest against the output surface
4. Try to change the text in the Ore Dic Filter to "*"

Crash report:
```
Description: Ticking block entity

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at gregtech.common.covers.CoverOreDictionaryFilter.oreDictionaryFilterMatch(CoverOreDictionaryFilter.java:186)
	at gregtech.common.covers.CoverOreDictionaryFilter$ItemHandlerOreDictFiltered.extractItem(CoverOreDictionaryFilter.java:162)
	at gregtech.api.metatileentity.MetaTileEntity.moveInventoryItems(MetaTileEntity.java:863)
	at gregtech.api.metatileentity.MetaTileEntity.pushItemsIntoNearbyHandlers(MetaTileEntity.java:837)
	at gregtech.api.metatileentity.SimpleMachineMetaTileEntity.update(SimpleMachineMetaTileEntity.java:107)
	at gregtech.api.metatileentity.MetaTileEntityHolder.func_73660_a(MetaTileEntityHolder.java:151)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:256)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.lang.String.substring(Unknown Source)
	at gregtech.common.covers.CoverOreDictionaryFilter.oreDictionaryFilterMatch(CoverOreDictionaryFilter.java:186)
	at gregtech.common.covers.CoverOreDictionaryFilter$ItemHandlerOreDictFiltered.extractItem(CoverOreDictionaryFilter.java:162)
	at gregtech.api.metatileentity.MetaTileEntity.moveInventoryItems(MetaTileEntity.java:863)
	at gregtech.api.metatileentity.MetaTileEntity.pushItemsIntoNearbyHandlers(MetaTileEntity.java:837)
	at gregtech.api.metatileentity.SimpleMachineMetaTileEntity.update(SimpleMachineMetaTileEntity.java:107)
	at gregtech.api.metatileentity.MetaTileEntityHolder.func_73660_a(MetaTileEntityHolder.java:151)

-- Block entity being ticked --
Details:
	Name: gregtech:machine // gregtech.api.metatileentity.MetaTileEntityHolder
	Block type: ID #385 (tile.unnamed // gregtech.api.block.machines.BlockMachine // gregtech:machine)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-65,71,267), Chunk: (at 15,4,11 in -5,16; contains blocks -80,0,256 to -65,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #385 (tile.unnamed // gregtech.api.block.machines.BlockMachine // gregtech:machine)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
```

**Comment by Archengius** [comment]
1/1 warning check opened issues before creating a duplicate

**Comment by KaneHart** [comment]
1/1 warning no downloadable fix.
