### ISSUE TITLE
Problems with removing recipes from machines by using CraftTweaker

### ISSUE THREAD

**Issue by HonzaVinCZ** [GregTechCE/GregTech#885]
Hello, I noticed I can't remove machine recipes by using CraftTweaker. This is my code I tried to use from CraftTweaker GTCE documentation:

_val macerator as RecipeMap = RecipeMap.getByName("macerator");

// findRecipe(long voltage, IItemHandlerModifiable inputs, IMultipleTankHandler/List<FluidStack> fluidInputs)
macerator.findRecipe(2, [<appliedenergistics2:material:3>], null).remove();_

It just doesn't work and reports this error:

_[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: vanilla.zs}
[INITIALIZATION][CLIENT][ERROR] vanilla.zs:1 > could not find type RecipeMap
[INITIALIZATION][CLIENT][ERROR] vanilla.zs:1 > could not find RecipeMap
[INITIALIZATION][CLIENT][ERROR] vanilla.zs:4 > any values not yet supported
[INITIALIZATION][CLIENT][ERROR] vanilla.zs:4 > any values not yet supported
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: vanilla.zs}: Bad type on operand stack
Exception Details:
  Location:
    Vanilla.__script__()V @23: invokestatic
  Reason:
    Type 'stanhebben/zenscript/value/IAny' (current frame, stack[4]) is not assignable to 'java/lang/String'
  Current Frame:
    bci: @23
    flags: { }
    locals: { }
    stack: { null, '[Lstanhebben/zenscript/value/IAny;', '[Lstanhebben/zenscript/value/IAny;', integer, 'stanhebben/zenscript/value/IAny' }
  Bytecode:
    0x0000000: 0112 0abd 000c 5912 0d12 0f59 c700 0857
    0x0000010: 01a7 0006 b800 15b8 001b 53b9 001f 0200
    0x0000020: 4c01 01b9 001f 0200 57b1               
  Stackmap Table:
    full_frame(@20,{},{Null,Object[#33],Object[#33],Integer,Object[#35]})
    full_frame(@23,{},{Null,Object[#33],Object[#33],Integer,Object[#12]})

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Vanilla.__script__()V @23: invokestatic
  Reason:
    Type 'stanhebben/zenscript/value/IAny' (current frame, stack[4]) is not assignable to 'java/lang/String'
  Current Frame:
    bci: @23
    flags: { }
    locals: { }
    stack: { null, '[Lstanhebben/zenscript/value/IAny;', '[Lstanhebben/zenscript/value/IAny;', integer, 'stanhebben/zenscript/value/IAny' }
  Bytecode:
    0x0000000: 0112 0abd 000c 5912 0d12 0f59 c700 0857
    0x0000010: 01a7 0006 b800 15b8 001b 53b9 001f 0200
    0x0000020: 4c01 01b9 001f 0200 57b1               
  Stackmap Table:
    full_frame(@20,{},{Null,Object[#33],Object[#33],Integer,Object[#35]})
    full_frame(@23,{},{Null,Object[#33],Object[#33],Integer,Object[#12]})

	at __ZenMain__.run(Vanilla)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:221)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:101)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:629)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)_

**Comment by Black0305** [comment]
Did you import RecipeMaps at the beginning of the script?
`import mods.gregtech.recipe.RecipeMap;`

**Comment by HonzaVinCZ** [comment]
> Did you import RecipeMaps at the beginning of the script?
> `import mods.gregtech.recipe.RecipeMap;`

I didn't that. Maybe that is the problem. But why adding recipes to the assembler is working without any importing? Just asking, I'm not sure why or how I must import some packages. 
One more question: 
Why there's that number 2 after findRecipe please. Not sure what's the point of that number there.
`macerator.findRecipe(2, [appliedenergistics2:material:3], null).remove();_`

**Comment by Archengius** [comment]
findRecipe(recipeEUt, inputs, fluidInputs)
There are examples pinned in discord channel. Ask for crafttweaker help in discord please.
