### ISSUE TITLE
Crash in ore gen

### ISSUE THREAD

**Issue by cam72cam** [GregTechCE/GregTech#891]
All default gregtech configs, version number in the crash report

```
[17:37:09] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1448) ~[?:1.8.0_212]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
	at gregtech.api.worldgen.generator.CachedGridEntry$ChunkDataEntry.populateChunk(CachedGridEntry.java:303) ~[CachedGridEntry$ChunkDataEntry.class:?]
	at gregtech.api.worldgen.generator.CachedGridEntry.populateChunk(CachedGridEntry.java:169) ~[CachedGridEntry.class:?]
	at gregtech.api.worldgen.generator.WorldGeneratorImpl.generateInternal(WorldGeneratorImpl.java:49) ~[WorldGeneratorImpl.class:?]
	at gregtech.api.worldgen.generator.WorldGeneratorImpl.generate(WorldGeneratorImpl.java:40) ~[WorldGeneratorImpl.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999) ~[axw.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:37) ~[and.class:?]
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:113) ~[ze.class:?]
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51) ~[zd.class:?]
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73) ~[zd.class:?]
	at net.minecraft.pathfinding.PathNavigate.func_75497_a(SourceFile:147) ~[ze.class:?]
	at net.minecraft.entity.ai.EntityAIFollowParent.func_75246_d(SourceFile:81) ~[xd.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) ~[xf.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888) ~[vq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678) ~[vq.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) ~[vd.class:?]
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43) ~[zv.class:?]
	at net.minecraft.entity.passive.AbstractHorse.func_70636_d(AbstractHorse.java:635) ~[aao.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377) ~[vq.class:?]
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682) ~[aao.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1993) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1955) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1759) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
```

```
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.19.0-5-amd64
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1062044688 bytes (1012 MB) / 3768057856 bytes (3593 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xms512m -Xmx6144m
	IntCache: cache: 12, tcache: 98, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                           | Signature                                |
	|:------ |:-------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                  | 9.42                     | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2838-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2838             | forge-1.12.2-14.23.5.2838-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jei                  | 4.15.0.268               | jei_1.12.2-4.15.0.268(1).jar                     | None                                     |
	| LCHIJA | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                       | None                                     |
	| LCHIJA | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| LCHIJA | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal(1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | controlling          | 3.0.7                    | Controlling-3.0.7.jar                            | None                                     |
	| LCHIJA | dynamictrees         | 1.12.2-0.9.5             | DynamicTrees-1.12.2-0.9.5.jar                    | None                                     |
	| LCHIJA | gregtech             | 1.8.4.419                | gregtech-1.12.2-1.8.4.419.jar                    | None                                     |
	| LCHIJA | trackapi             | 1.1                      | TrackAPI-1.1_1.12(2).jar                         | None                                     |
	| LCHIJA | immersiverailroading | 1.6.1                    | ImmersiveRailroading-1.6.1_1.12-1138(2).jar      | None                                     |
	| LCHIJA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63(1).jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | journeymap           | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                      | None                                     |
	| LCHIJA | mousetweaks          | 2.10                     | MouseTweaks-2.10-mc1.12.2(1).jar                 | None                                     |
	| LCHIJA | prospectus           | 1.8                      | prospectus-1.8.jar                               | None                                     |
	| LCHIJA | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                  | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63(1).jar)
  invtweaks.forge.asm.ContainerTransformer
```

**Comment by Archengius** [comment]
cannot reproduce, i can't find obvious reason of null pointer deep in JVM internals. Try updating GTCE version and JRE.

**Comment by cam72cam** [comment]
lol, deep in JVM internals.  That's just a null check from something you pass in 2 layers deep.
