### ISSUE TITLE
Error While Adding Recipes

### ISSUE THREAD

**Issue by HansscMe** [GregTechCE/GregTech#899]
Hello,
I have an error while starting up gregtech.
Could you please help me ?

```
[12:38:43] [Server thread/ERROR] [gregtech]: Tried to register recipe, mortar_grind_lead, with duplicate key. Recipe: "X", "m", "X", "ingotLead"
[12:38:43] [Server thread/ERROR] [gregtech]: Stacktrace:
java.lang.IllegalArgumentException: null
        at gregtech.api.recipes.ModHandler.validateRecipe(ModHandler.java:357) ~[ModHandler.class:?]
        at gregtech.api.recipes.ModHandler.addShapedRecipe(ModHandler.java:281) ~[ModHandler.class:?]
        at gregtech.loaders.oreprocessing.MaterialRecipeHandler.processIngot(MaterialRecipeHandler.java:185) ~[MaterialRecipeHandler.class:?]
        at gregtech.api.unification.ore.OrePrefix.lambda$addProcessingHandler$39(OrePrefix.java:389) ~[OrePrefix.class:?]
        at gregtech.api.unification.ore.OrePrefix.runGeneratedMaterialHandlers(OrePrefix.java:425) [OrePrefix.class:?]
        at gregtech.api.unification.ore.OrePrefix.runMaterialHandlers(OrePrefix.java:405) [OrePrefix.class:?]
        at gregtech.common.CommonProxy.registerRecipesLowest(CommonProxy.java:171) [CommonProxy.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_145_CommonProxy_registerRecipesLowest_Register.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) [EventBus$1.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1255) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1202) [EventBus.class:?]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857) [GameData.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:629) [CraftingHelper.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[12:38:43] [Server thread/ERROR] [gregtech]: Tried to register recipe, stick_lead, with duplicate key. Recipe: "f ", " X", "X", "ingotLead"
[12:38:43] [Server thread/ERROR] [gregtech]: Stacktrace:
java.lang.IllegalArgumentException: null
        at gregtech.api.recipes.ModHandler.validateRecipe(ModHandler.java:357) ~[ModHandler.class:?]
        at gregtech.api.recipes.ModHandler.addShapedRecipe(ModHandler.java:281) ~[ModHandler.class:?]
        at gregtech.loaders.oreprocessing.MaterialRecipeHandler.processIngot(MaterialRecipeHandler.java:196) ~[MaterialRecipeHandler.class:?]
        at gregtech.api.unification.ore.OrePrefix.lambda$addProcessingHandler$39(OrePrefix.java:389) ~[OrePrefix.class:?]
        at gregtech.api.unification.ore.OrePrefix.runGeneratedMaterialHandlers(OrePrefix.java:425) [OrePrefix.class:?]
        at gregtech.api.unification.ore.OrePrefix.runMaterialHandlers(OrePrefix.java:405) [OrePrefix.class:?]
        at gregtech.common.CommonProxy.registerRecipesLowest(CommonProxy.java:171) [CommonProxy.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_145_CommonProxy_registerRecipesLowest_Register.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) [EventBus$1.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1255) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1202) [EventBus.class:?]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857) [GameData.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:629) [CraftingHelper.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[12:38:43] [Server thread/ERROR] [gregtech]: Tried to register recipe, plate_lead, with duplicate key. Recipe: "h", "I", "I", "I", "ingotLead"
[12:38:43] [Server thread/ERROR] [gregtech]: Stacktrace:
java.lang.IllegalArgumentException: null
        at gregtech.api.recipes.ModHandler.validateRecipe(ModHandler.java:357) ~[ModHandler.class:?]
        at gregtech.api.recipes.ModHandler.addShapedRecipe(ModHandler.java:281) ~[ModHandler.class:?]
        at gregtech.loaders.oreprocessing.MaterialRecipeHandler.processIngot(MaterialRecipeHandler.java:262) ~[MaterialRecipeHandler.class:?]
        at gregtech.api.unification.ore.OrePrefix.lambda$addProcessingHandler$39(OrePrefix.java:389) ~[OrePrefix.class:?]
        at gregtech.api.unification.ore.OrePrefix.runGeneratedMaterialHandlers(OrePrefix.java:425) [OrePrefix.class:?]
        at gregtech.api.unification.ore.OrePrefix.runMaterialHandlers(OrePrefix.java:405) [OrePrefix.class:?]
        at gregtech.common.CommonProxy.registerRecipesLowest(CommonProxy.java:171) [CommonProxy.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_145_CommonProxy_registerRecipesLowest_Register.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) [EventBus$1.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1255) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1202) [EventBus.class:?]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857) [GameData.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:629) [CraftingHelper.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```
My mod list:
`Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Academy Craft, Another Common Bug Fix, AnotherAntiCheat Mod, Astral Sorcery, Baubles, Botania, CodeChicken Lib, CustomNPCs, DummyCoreUnofficial, Extra Planets, Forestry, Galacticraft Core, Galacticraft Planets, GregTech Community Edition, Hammer Core, IndustrialCraft 2, LagGoggles, LambdaLib2|Core, MJRLegendsLib, MagicBees, Mantle, Micdoodle8 Core, Phosphor Lighting Engine, PlusTiC, SpongeForge, TeaStory, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Bases, Tinkers' Construct, Tiquality, lambdalib2`

FML Version: 2838
GT Version: 419

Thank you!

**Comment by Agrax** [comment]
I might be totes wrong but to my unrefined eye it looks like you were trying to make a lead mortar when there might already be one: thus the „duplicate key” error

**Comment by HansscMe** [comment]
> I might be totes wrong but to my unrefined eye it looks like you were trying to make a recipe to grind lead ingots when there might already be one: thus the „duplicate key” error
> 
> You were using CT, weren’t ya?

This error happens when starting up.

**Comment by Agrax** [comment]
It doesn’t answer my question

**Comment by HansscMe** [comment]
It happens when Galacticraft is enabled.

I just want to know how to solve it.

**Comment by Archengius** [comment]
then it's galacticraft issue
