### ISSUE TITLE
NullPointer Farming Station GregTech Tool

### ISSUE THREAD

**Issue by zocke1r** [GregTechCE/GregTech#921]
GTCE Version: gregtech-1.12.2-1.8.4.419
Modpack: Omnifactory V1.2.1

Whenever I place a GregTech Axe into my EnderIO Farming station i get a Nullpointer Exception

Stacktrace:
java.lang.NullPointerException: Updating screen events
	at gregtech.common.tools.ToolAxe.canMineBlock(ToolAxe.java:50)
	at gregtech.api.items.toolitem.ToolMetaItem.getHarvestLevel(ToolMetaItem.java:254)
	at crazypants.enderio.base.farming.FarmingTool$3.match(FarmingTool.java:33)
	at crazypants.enderio.base.farming.FarmingTool.itemMatches(FarmingTool.java:65)
	at crazypants.enderio.base.farming.FarmingTool.getToolType(FarmingTool.java:82)

 
[crash-2019-07-20_12.07.56-client.txt](https://github.com/GregTechCE/GregTech/files/3413495/crash-2019-07-20_12.07.56-client.txt)

**Comment by Agrax** [comment]
I can only guess it’s an EIO issue, not GT. Report accordingly

**Comment by Archengius** [comment]
EIO issue passing null to methods not expecting null. I added null check tho.
