### ISSUE TITLE
ClassCastException When Opening Storage Drawer with Aluminium Inside

### ISSUE THREAD

**Issue by zocke1r** [GregTechCE/GregTech#922]
GTCE Version: gregtech-1.12.2-1.8.4.419
Modpack: Omnifactory V1.2.1

When i ever i try to open my storage drawer containing aluminium to change the storage upgrade, i get this exception:
```
java.lang.ClassCastException: appeng.items.misc.ItemEncodedPattern cannot be cast to gregtech.common.pipelike.cable.ItemBlockCable
	at gregtech.common.render.CableRenderer.renderItem(CableRenderer.java:95)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:207)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.StorageRenderItem.func_180454_a(StorageRenderItem.java:47)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:517)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:559)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at com.jaquadro.minecraft.storagedrawers.client.gui.GuiDrawers.func_73863_a(GuiDrawers.java:74)
```

[crash-2019-07-23_21.05.43-client.txt](https://github.com/GregTechCE/GregTech/files/3423707/crash-2019-07-23_21.05.43-client.txt)

**Comment by Blood-Asp** [comment]
well, just a guess: do you have an AE2 pattern with an recipe for GT cabel/wire or pipe in your inventory while opening the storage drawer?

I know that AE2 pattern do not render many GT blocks, but it itself does prevent any crash.

**Comment by Archengius** [comment]
Your description of issue is incorrect. Exception is from rendering AE2 storage pattern with GTCE item. Not going to be fixed.

**Comment by Archengius** [comment]
Actually, I can make it a bit better by using different item rendering technique

**Comment by Archengius** [comment]
Fixed in latest commit
