### ISSUE TITLE
Multismelter deletes results if output is full

### ISSUE THREAD

**Issue by bondus** [GregTechCE/GregTech#931]
A multismelter with upgraded coils that does multiple stacks at once will start smelting multiple stacks before there is room in the output. The overflow of the smelt is deleted. 

I'm running gregtech-1.12.2-1.8.4.419 from curse.

It logs an error at the same time: 

[22:27:49] [Server thread/ERROR] [gregtech]: Invalid amount of recipe inputs. Actual: 3. Should be between 1 and 1 inclusive.
[22:27:49] [Server thread/ERROR] [gregtech]: Stacktrace:
java.lang.IllegalArgumentException: null
        at gregtech.api.recipes.RecipeBuilder.validate(RecipeBuilder.java:272) [RecipeBuilder.class:?]
        at gregtech.api.recipes.RecipeBuilder.finalizeAndValidate(RecipeBuilder.java:259) [RecipeBuilder.class:?]
        at gregtech.api.recipes.builders.SimpleRecipeBuilder.build(SimpleRecipeBuilder.java:28) [SimpleRecipeBuilder.class:?]
        at gregtech.common.metatileentities.multi.electric.MetaTileEntityMultiFurnace$MultiFurnaceWorkable.findRecipe(MetaTileEntityMultiFurnace.java:165) [MetaTileEntityMultiFurnace$MultiFurnaceWorkable.class:?]
        at gregtech.common.metatileentities.multi.electric.MetaTileEntityMultiFurnace$MultiFurnaceWorkable.trySearchNewRecipe(MetaTileEntityMultiFurnace.java:119) [MetaTileEntityMultiFurnace$MultiFurnaceWorkable.class:?]
        at gregtech.api.capability.impl.AbstractRecipeLogic.update(AbstractRecipeLogic.java:109) [AbstractRecipeLogic.class:?]
        at gregtech.api.capability.impl.MultiblockRecipeLogic.updateWorkable(MultiblockRecipeLogic.java:21) [MultiblockRecipeLogic.class:?]
        at gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController.updateFormedValid(RecipeMapMultiblockController.java:92) [RecipeMapMultiblockController.class:?]
        at gregtech.api.metatileentity.multiblock.MultiblockControllerBase.update(MultiblockControllerBase.java:54) [MultiblockControllerBase.class:?]
        at gregtech.api.metatileentity.MetaTileEntityHolder.func_73660_a(MetaTileEntityHolder.java:152) [MetaTileEntityHolder.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1835) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by bondus** [comment]
The error shown above is not related to the deleting of items.
It seems like all GTCE machine with more than one stack of output will start running when there is one slot free in the output slot, and delete the items that does not fit.

**Comment by Josh5minus1** [comment]
You need enough space for the output bus to store the items without voiding

**Comment by Archengius** [comment]
cannot reproduce output deletion

**Comment by Blood-Asp** [comment]
I know of multiple ways that void recipe outputs:
For the multismelter it needs smelts that output multiple items from a single input. Example Apatite ore. Upgrade the multismelter that it can smelt a whole stack at once and give it an output bus that only has 1 or 4 slots. The process will start and since apaite produces 5 gems per ore it produces 5 stacks. These 5 stacks do not fit into the output bus, so the reminder will be voided.

Another way that did annoy me a lot: HV+ macerator with chance output.
Process ore, but only take out the crushed ore, but not the chanced metal and stone dusts. The processing will keep working as long there is space for the crushed ore, but it does not care about the full dusts and void them like an low tier macerator that does not have that slots.

**Comment by Archengius** [comment]
Second is not valid for at least 4 builds now
